:- module(negprefix, [negprefix/4]).

negprefix(a, unthematic, un, thematic).
negprefix(a, inhospitable, in, hospitable).
negprefix(a, untrimmed, un, trimmed).
negprefix(a, unfunded, un, funded).
negprefix(a, incurious, in, curious).
negprefix(a, imperceptible, im, perceptible).
negprefix(a, unenforced, un, enforced).
negprefix(a, unrhythmical, un, rhythmical).
negprefix(a, unbrainwashed, un, brainwashed).
negprefix(a, uncompromising, un, compromising).
negprefix(a, untreated, un, treated).
negprefix(a, undesirable, un, desirable).
negprefix(a, uneasy, un, easy).
negprefix(a, indigestible, in, digestible).
negprefix(a, noninfectious, non, infectious).
negprefix(a, unmown, un, mown).
negprefix(a, unmelodious, un, melodious).
negprefix(a, untalented, un, talented).
negprefix(a, nonprehensile, non, prehensile).
negprefix(a, inconstant, in, constant).
negprefix(a, unenforceable, un, enforceable).
negprefix(a, unable, un, able).
negprefix(a, unadventurous, un, adventurous).
negprefix(a, apetalous, a, petalous).
negprefix(a, unshod, un, shod).
negprefix(a, unendowed, un, endowed).
negprefix(a, indestructible, in, destructible).
negprefix(a, impermissible, im, permissible).
negprefix(a, uncombined, un, combined).
negprefix(a, unnoticeable, un, noticeable).
negprefix(a, noncolumned, non, columned).
negprefix(a, unlubricated, un, lubricated).
negprefix(a, uninjured, un, injured).
negprefix(a, unwieldy, un, wieldy).
negprefix(a, uncongenial, un, congenial).
negprefix(a, unscheduled, un, scheduled).
negprefix(a, insolvent, in, solvent).
negprefix(a, unshelled, un, shelled).
negprefix(a, unfaithful, un, faithful).
negprefix(a, incorrigible, in, corrigible).
negprefix(a, infelicitous, in, felicitous).
negprefix(a, nonparticulate, non, particulate).
negprefix(a, unpotted, un, potted).
negprefix(a, nonhierarchical, non, hierarchical).
negprefix(a, unethical, un, ethical).
negprefix(a, uncoiled, un, coiled).
negprefix(a, undesirous, un, desirous).
negprefix(a, nonunion, non, union).
negprefix(a, unoriginal, un, original).
negprefix(a, noncausative, non, causative).
negprefix(a, unintelligible, un, intelligible).
negprefix(a, unaddicted, un, addicted).
negprefix(a, nonmetallic, non, metallic).
negprefix(a, unspecified, un, specified).
negprefix(a, unprofitable, un, profitable).
negprefix(a, immiscible, im, miscible).
negprefix(a, indiscreet, in, discreet).
negprefix(a, unconvinced, un, convinced).
negprefix(a, unassertive, un, assertive).
negprefix(a, unwomanly, un, womanly).
negprefix(a, unarticulated, un, articulated).
negprefix(a, noncyclic, non, cyclic).
negprefix(a, unrestrictive, un, restrictive).
negprefix(a, unreserved, un, reserved).
negprefix(a, noncellular, non, cellular).
negprefix(a, unfixed, un, fixed).
negprefix(a, incautious, in, cautious).
negprefix(a, unfinished, un, finished).
negprefix(a, noncritical, non, critical).
negprefix(a, unprotective, un, protective).
negprefix(a, inaccessible, in, accessible).
negprefix(a, unpardonable, un, pardonable).
negprefix(a, inanimate, in, animate).
negprefix(a, unwanted, un, wanted).
negprefix(a, untimbered, un, timbered).
negprefix(a, unexcitable, un, excitable).
negprefix(a, irrelevant, ir, relevant).
negprefix(a, disarranged, dis, arranged).
negprefix(a, unfaceted, un, faceted).
negprefix(a, insentient, in, sentient).
negprefix(a, unconscious, un, conscious).
negprefix(a, uncooperative, un, cooperative).
negprefix(a, nonpartisan, non, partisan).
negprefix(a, untroubled, un, troubled).
negprefix(a, uncontrolled, un, controlled).
negprefix(a, nonindulgent, non, indulgent).
negprefix(a, unenthusiastic, un, enthusiastic).
negprefix(a, unfretted, un, fretted).
negprefix(a, irremediable, ir, remediable).
negprefix(a, uninterested, un, interested).
negprefix(a, unsettled, un, settled).
negprefix(a, unfurrowed, un, furrowed).
negprefix(a, nondeductible, non, deductible).
negprefix(a, atonal, a, tonal).
negprefix(a, inattentive, in, attentive).
negprefix(a, uncaulked, un, caulked).
negprefix(a, ungrateful, un, grateful).
negprefix(a, unlaced, un, laced).
negprefix(a, nonalcoholic, non, alcoholic).
negprefix(a, nonreciprocal, non, reciprocal).
negprefix(a, invisible, in, visible).
negprefix(a, unpackaged, un, packaged).
negprefix(a, unregulated, un, regulated).
negprefix(a, unpropitious, un, propitious).
negprefix(a, untempered, un, tempered).
negprefix(a, unsarcastic, un, sarcastic).
negprefix(a, disadvantageous, dis, advantageous).
negprefix(a, undefined, un, defined).
negprefix(a, inorganic, in, organic).
negprefix(a, undue, un, due).
negprefix(a, unselected, un, selected).
negprefix(a, immaterial, im, material).
negprefix(a, unagitated, un, agitated).
negprefix(a, anaphrodisiac, an, aphrodisiac).
negprefix(a, unprecedented, un, precedented).
negprefix(a, insufficient, in, sufficient).
negprefix(a, nonpasserine, non, passerine).
negprefix(a, unplanned, un, planned).
negprefix(a, unimportant, un, important).
negprefix(a, unexpansive, un, expansive).
negprefix(a, unadorned, un, adorned).
negprefix(a, unofficial, un, official).
negprefix(a, achlamydeous, a, chlamydeous).
negprefix(a, inaesthetic, in, aesthetic).
negprefix(a, unlucky, un, lucky).
negprefix(a, uninteresting, un, interesting).
negprefix(a, untraceable, un, traceable).
negprefix(a, unwritten, un, written).
negprefix(a, unshared, un, shared).
negprefix(a, unframed, un, framed).
negprefix(a, unconfirmed, un, confirmed).
negprefix(a, uncousinly, un, cousinly).
negprefix(a, unseductive, un, seductive).
negprefix(a, undatable, un, datable).
negprefix(a, unabridged, un, abridged).
negprefix(a, unaccompanied, un, accompanied).
negprefix(a, nonspeaking, non, speaking).
negprefix(a, unbodied, un, bodied).
negprefix(a, nonproprietary, non, proprietary).
negprefix(a, unregistered, un, registered).
negprefix(a, inefficacious, in, efficacious).
negprefix(a, nonsectarian, non, sectarian).
negprefix(a, impartial, im, partial).
negprefix(a, unwilling, un, willing).
negprefix(a, unknowable, un, knowable).
negprefix(a, infallible, in, fallible).
negprefix(a, dissimilar, dis, similar).
negprefix(a, nonrepresentational, non, representational).
negprefix(a, unfruitful, un, fruitful).
negprefix(a, unmusical, un, musical).
negprefix(a, unchanged, un, changed).
negprefix(a, unpunished, un, punished).
negprefix(a, incomprehensible, in, comprehensible).
negprefix(a, nonconductive, non, conductive).
negprefix(a, uneven, un, even).
negprefix(a, nonfissionable, non, fissionable).
negprefix(a, uncritical, un, critical).
negprefix(a, unhealthful, un, healthful).
negprefix(a, unthinkable, un, thinkable).
negprefix(a, uneducated, un, educated).
negprefix(a, unmarried, un, married).
negprefix(a, noncurrent, non, current).
negprefix(a, unsolved, un, solved).
negprefix(a, uncorrected, un, corrected).
negprefix(a, untrained, un, trained).
negprefix(a, unreported, un, reported).
negprefix(a, nonnative, non, native).
negprefix(a, irreconcilable, ir, reconcilable).
negprefix(a, impermeable, im, permeable).
negprefix(a, unturned, un, turned).
negprefix(a, unclean, un, clean).
negprefix(a, unbeneficed, un, beneficed).
negprefix(a, unwelcome, un, welcome).
negprefix(a, innumerate, in, numerate).
negprefix(a, unbaptized, un, baptized).
negprefix(a, unexpired, un, expired).
negprefix(a, uninvolved, un, involved).
negprefix(a, unreconstructed, un, reconstructed).
negprefix(a, inconclusive, in, conclusive).
negprefix(a, asymmetrical, a, symmetrical).
negprefix(a, unstatesmanlike, un, statesmanlike).
negprefix(a, inextinguishable, in, extinguishable).
negprefix(a, unfair, un, fair).
negprefix(a, displeased, dis, pleased).
negprefix(a, unnatural, un, natural).
negprefix(a, 'uncared-for', un, 'cared-for').
negprefix(a, unfueled, un, fueled).
negprefix(a, unclothed, un, clothed).
negprefix(a, untruthful, un, truthful).
negprefix(a, adiabatic, a, diabatic).
negprefix(a, untheatrical, un, theatrical).
negprefix(a, unargumentative, un, argumentative).
negprefix(a, inaudible, in, audible).
negprefix(a, unerect, un, erect).
negprefix(a, unperceptive, un, perceptive).
negprefix(a, astomatous, a, stomatous).
negprefix(a, inconsolable, in, consolable).
negprefix(a, undetermined, un, determined).
negprefix(a, nonfatal, non, fatal).
negprefix(a, nonprofessional, non, professional).
negprefix(a, undignified, un, dignified).
negprefix(a, unprofessional, un, professional).
negprefix(a, unhealthy, un, healthy).
negprefix(a, unseasoned, un, seasoned).
negprefix(a, asexual, a, sexual).
negprefix(a, unoffending, un, offending).
negprefix(a, nonastringent, non, astringent).
negprefix(a, unproductive, un, productive).
negprefix(a, imperfect, im, perfect).
negprefix(a, uninhabited, un, inhabited).
negprefix(a, nonadsorbent, non, adsorbent).
negprefix(a, nonruminant, non, ruminant).
negprefix(a, unrighteous, un, righteous).
negprefix(a, inefficient, in, efficient).
negprefix(a, insecure, in, secure).
negprefix(a, unregenerate, un, regenerate).
negprefix(a, unamended, un, amended).
negprefix(a, indecisive, in, decisive).
negprefix(a, indispensable, in, dispensable).
negprefix(a, unironed, un, ironed).
negprefix(a, nontaxable, non, taxable).
negprefix(a, unintrusive, un, intrusive).
negprefix(a, inopportune, in, opportune).
negprefix(a, unsystematic, un, systematic).
negprefix(a, nonreticulate, non, reticulate).
negprefix(a, irresponsible, ir, responsible).
negprefix(a, unfocused, un, focused).
negprefix(a, dishonest, dis, honest).
negprefix(a, irreversible, ir, reversible).
negprefix(a, unstuck, un, stuck).
negprefix(a, unreasonable, un, reasonable).
negprefix(a, unneurotic, un, neurotic).
negprefix(a, unglazed, un, glazed).
negprefix(a, ungathered, un, gathered).
negprefix(a, unwoven, un, woven).
negprefix(a, unfledged, un, fledged).
negprefix(a, unworthy, un, worthy).
negprefix(a, unsupervised, un, supervised).
negprefix(a, unvaried, un, varied).
negprefix(a, unprintable, un, printable).
negprefix(a, uninformed, un, informed).
negprefix(a, uncharged, un, charged).
negprefix(a, unambitious, un, ambitious).
negprefix(a, unwitting, un, witting).
negprefix(a, unlaureled, un, laureled).
negprefix(a, unsheared, un, sheared).
negprefix(a, uneventful, un, eventful).
negprefix(a, uncleared, un, cleared).
negprefix(a, disordered, dis, ordered).
negprefix(a, nonindustrial, non, industrial).
negprefix(a, unscientific, un, scientific).
negprefix(a, nonracial, non, racial).
negprefix(a, immutable, im, mutable).
negprefix(a, noninstitutional, non, institutional).
negprefix(a, undefeated, un, defeated).
negprefix(a, unequal, un, equal).
negprefix(a, incommutable, in, commutable).
negprefix(a, uncommitted, un, committed).
negprefix(a, unsound, un, sound).
negprefix(a, nonsignificant, non, significant).
negprefix(a, nonjudgmental, non, judgmental).
negprefix(a, unsinkable, un, sinkable).
negprefix(a, unopposed, un, opposed).
negprefix(a, uncertain, un, certain).
negprefix(a, unpolished, un, polished).
negprefix(a, nonlinguistic, non, linguistic).
negprefix(a, unstoppable, un, stoppable).
negprefix(a, uncrowned, un, crowned).
negprefix(a, unpunctual, un, punctual).
negprefix(a, unloaded, un, loaded).
negprefix(a, unbroken, un, broken).
negprefix(a, unservile, un, servile).
negprefix(a, intransitive, in, transitive).
negprefix(a, ununderstood, un, understood).
negprefix(a, unskilled, un, skilled).
negprefix(a, ahistorical, a, historical).
negprefix(a, ineligible, in, eligible).
negprefix(a, unmanageable, un, manageable).
negprefix(a, unapproachable, un, approachable).
negprefix(a, unexploited, un, exploited).
negprefix(a, unsexy, un, sexy).
negprefix(a, noninheritable, non, inheritable).
negprefix(a, unbelted, un, belted).
negprefix(a, illicit, il, licit).
negprefix(a, nonoperational, non, operational).
negprefix(a, undeniable, un, deniable).
negprefix(a, noncombustible, non, combustible).
negprefix(a, untraveled, un, traveled).
negprefix(a, unconscientious, un, conscientious).
negprefix(a, untouched, un, touched).
negprefix(a, inactive, in, active).
negprefix(a, nontoxic, non, toxic).
negprefix(a, uncollected, un, collected).
negprefix(a, irrational, ir, rational).
negprefix(a, disliked, dis, liked).
negprefix(a, unexpected, un, expected).
negprefix(a, unborn, un, born).
negprefix(a, unprejudiced, un, prejudiced).
negprefix(a, unchaste, un, chaste).
negprefix(a, unconventional, un, conventional).
negprefix(a, inalienable, in, alienable).
negprefix(a, incredulous, in, credulous).
negprefix(a, anonymous, an, onymous).
negprefix(a, unpatronized, un, patronized).
negprefix(a, uncommunicative, un, communicative).
negprefix(a, irresolute, ir, resolute).
negprefix(a, nonmonotonic, non, monotonic).
negprefix(a, unsworn, un, sworn).
negprefix(a, uncompassionate, un, compassionate).
negprefix(a, noncommissioned, non, commissioned).
negprefix(a, inarticulate, in, articulate).
negprefix(a, unwrapped, un, wrapped).
negprefix(a, unfeathered, un, feathered).
negprefix(a, untranslatable, un, translatable).
negprefix(a, indecent, in, decent).
negprefix(a, unshuttered, un, shuttered).
negprefix(a, noncivilized, non, civilized).
negprefix(a, unexchangeable, un, exchangeable).
negprefix(a, unmodulated, un, modulated).
negprefix(a, unshapely, un, shapely).
negprefix(a, intestate, in, testate).
negprefix(a, irrevocable, ir, revocable).
negprefix(a, azonal, a, zonal).
negprefix(a, unimpaired, un, impaired).
negprefix(a, unrevived, un, revived).
negprefix(a, indivisible, in, divisible).
negprefix(a, analphabetic, an, alphabetic).
negprefix(a, insoluble, in, soluble).
negprefix(a, unlikely, un, likely).
negprefix(a, uncamphorated, un, camphorated).
negprefix(a, unbranded, un, branded).
negprefix(a, uncolored, un, colored).
negprefix(a, unscalable, un, scalable).
negprefix(a, nonrepresentative, non, representative).
negprefix(a, uncarpeted, un, carpeted).
negprefix(a, nonphotosynthetic, non, photosynthetic).
negprefix(a, uncomplaining, un, complaining).
negprefix(a, unburied, un, buried).
negprefix(a, nonlinear, non, linear).
negprefix(a, infrequent, in, frequent).
negprefix(a, discalced, dis, calced).
negprefix(a, uncharitable, un, charitable).
negprefix(a, unrespectable, un, respectable).
negprefix(a, undynamic, un, dynamic).
negprefix(a, nonbearing, non, bearing).
negprefix(a, unloving, un, loving).
negprefix(a, unburdened, un, burdened).
negprefix(a, impenitent, im, penitent).
negprefix(a, unpainted, un, painted).
negprefix(a, unmined, un, mined).
negprefix(a, unplowed, un, plowed).
negprefix(a, unhelpful, un, helpful).
negprefix(a, inessential, in, essential).
negprefix(a, unsized, un, sized).
negprefix(a, ungracious, un, gracious).
negprefix(a, unfamiliar, un, familiar).
negprefix(a, intractable, in, tractable).
negprefix(a, unenlightening, un, enlightening).
negprefix(a, unemotional, un, emotional).
negprefix(a, unshockable, un, shockable).
negprefix(a, undeciphered, un, deciphered).
negprefix(a, nonmodern, non, modern).
negprefix(a, uncastrated, un, castrated).
negprefix(a, unspecialized, un, specialized).
negprefix(a, unexhausted, un, exhausted).
negprefix(a, undomestic, un, domestic).
negprefix(a, impolitic, im, politic).
negprefix(a, impure, im, pure).
negprefix(a, unsealed, un, sealed).
negprefix(a, dishonorable, dis, honorable).
negprefix(a, unliveried, un, liveried).
negprefix(a, unanimated, un, animated).
negprefix(a, unmoved, un, moved).
negprefix(a, impious, im, pious).
negprefix(a, unaltered, un, altered).
negprefix(a, unlawful, un, lawful).
negprefix(a, discontented, dis, contented).
negprefix(a, unawed, un, awed).
negprefix(a, nonreversible, non, reversible).
negprefix(a, unprotected, un, protected).
negprefix(a, undocumented, un, documented).
negprefix(a, unoiled, un, oiled).
negprefix(a, inoffensive, in, offensive).
negprefix(a, unsaturated, un, saturated).
negprefix(a, unsavory, un, savory).
negprefix(a, uninquiring, un, inquiring).
negprefix(a, uncultivated, un, cultivated).
negprefix(a, insubstantial, in, substantial).
negprefix(a, unsent, un, sent).
negprefix(a, unbalanced, un, balanced).
negprefix(a, unleaded, un, leaded).
negprefix(a, inconvenient, in, convenient).
negprefix(a, disenchanted, dis, enchanted).
negprefix(a, nonstandard, non, standard).
negprefix(a, unmoving, un, moving).
negprefix(a, unrequested, un, requested).
negprefix(a, unlabeled, un, labeled).
negprefix(a, nonspherical, non, spherical).
negprefix(a, inappropriate, in, appropriate).
negprefix(a, inoperable, in, operable).
negprefix(a, unreverberant, un, reverberant).
negprefix(a, nonthermal, non, thermal).
negprefix(a, unrecoverable, un, recoverable).
negprefix(a, inexpressible, in, expressible).
negprefix(a, unstable, un, stable).
negprefix(a, nonharmonic, non, harmonic).
negprefix(a, uncombed, un, combed).
negprefix(a, unaffected, un, affected).
negprefix(a, incompatible, in, compatible).
negprefix(a, irreverent, ir, reverent).
negprefix(a, immature, im, mature).
negprefix(a, nontranslational, non, translational).
negprefix(a, undamaged, un, damaged).
negprefix(a, nonfissile, non, fissile).
negprefix(a, 'non-invertible', 'non-', invertible).
negprefix(a, unshaded, un, shaded).
negprefix(a, unchristian, un, christian).
negprefix(a, unscripted, un, scripted).
negprefix(a, unaffixed, un, affixed).
negprefix(a, displeasing, dis, pleasing).
negprefix(a, improper, im, proper).
negprefix(a, unemployed, un, employed).
negprefix(a, unclear, un, clear).
negprefix(a, unobvious, un, obvious).
negprefix(a, nonextensile, non, extensile).
negprefix(a, nonmechanical, non, mechanical).
negprefix(a, unplayable, un, playable).
negprefix(a, asyndetic, a, syndetic).
negprefix(a, disreputable, dis, reputable).
negprefix(a, inoperative, in, operative).
negprefix(a, inharmonious, in, harmonious).
negprefix(a, unadoptable, un, adoptable).
negprefix(a, unworldly, un, worldly).
negprefix(a, unpriestly, un, priestly).
negprefix(a, incontestable, in, contestable).
negprefix(a, inauspicious, in, auspicious).
negprefix(a, unmitigated, un, mitigated).
negprefix(a, unrhetorical, un, rhetorical).
negprefix(a, unrepeatable, un, repeatable).
negprefix(a, irregular, ir, regular).
negprefix(a, inexcusable, in, excusable).
negprefix(a, uninviting, un, inviting).
negprefix(a, nonsubmersible, non, submersible).
negprefix(a, unrifled, un, rifled).
negprefix(a, nonechoic, non, echoic).
negprefix(a, discontinuous, dis, continuous).
negprefix(a, untrustworthy, un, trustworthy).
negprefix(a, unequivocal, un, equivocal).
negprefix(a, unmelted, un, melted).
negprefix(a, acatalectic, a, catalectic).
negprefix(a, unspaced, un, spaced).
negprefix(a, noncollapsible, non, collapsible).
negprefix(a, untapped, un, tapped).
negprefix(a, impassable, im, passable).
negprefix(a, untidy, un, tidy).
negprefix(a, undependable, un, dependable).
negprefix(a, incorrupt, in, corrupt).
negprefix(a, incredible, in, credible).
negprefix(a, ungrammatical, un, grammatical).
negprefix(a, unsheathed, un, sheathed).
negprefix(a, uneager, un, eager).
negprefix(a, intolerable, in, tolerable).
negprefix(a, unedifying, un, edifying).
negprefix(a, unbound, un, bound).
negprefix(a, inhumane, in, humane).
negprefix(a, insensitive, in, sensitive).
negprefix(a, acaulescent, a, caulescent).
negprefix(a, unplanted, un, planted).
negprefix(a, unproved, un, proved).
negprefix(a, unencumbered, un, encumbered).
negprefix(a, unpaid, un, paid).
negprefix(a, unrigged, un, rigged).
negprefix(a, unestablished, un, established).
negprefix(a, unflattering, un, flattering).
negprefix(a, nonassociative, non, associative).
negprefix(a, unconcealed, un, concealed).
negprefix(a, nonionic, non, ionic).
negprefix(a, unpopular, un, popular).
negprefix(a, untipped, un, tipped).
negprefix(a, unoriented, un, oriented).
negprefix(a, insane, in, sane).
negprefix(a, imperishable, im, perishable).
negprefix(a, indistinct, in, distinct).
negprefix(a, achondritic, a, chondritic).
negprefix(a, nonexploratory, non, exploratory).
negprefix(a, unattractive, un, attractive).
negprefix(a, unadaptable, un, adaptable).
negprefix(a, nonresidential, non, residential).
negprefix(a, unsure, un, sure).
negprefix(a, nonpolitical, non, political).
negprefix(a, undedicated, un, dedicated).
negprefix(a, unstructured, un, structured).
negprefix(a, undemonstrative, un, demonstrative).
negprefix(a, unready, un, ready).
negprefix(a, illegal, il, legal).
negprefix(a, anastigmatic, an, astigmatic).
negprefix(a, undeveloped, un, developed).
negprefix(a, unostentatious, un, ostentatious).
negprefix(a, uncrossed, un, crossed).
negprefix(a, disintegrative, dis, integrative).
negprefix(a, uninformative, un, informative).
negprefix(a, nonabsorbent, non, absorbent).
negprefix(a, unfit, un, fit).
negprefix(a, unfurnished, un, furnished).
negprefix(a, unsteady, un, steady).
negprefix(a, unprovocative, un, provocative).
negprefix(a, unairworthy, un, airworthy).
negprefix(a, unsurprised, un, surprised).
negprefix(a, intolerant, in, tolerant).
negprefix(a, achromatic, a, chromatic).
negprefix(a, implausible, im, plausible).
negprefix(a, unafraid, un, afraid).
negprefix(a, unmanly, un, manly).
negprefix(a, indecorous, in, decorous).
negprefix(a, impervious, im, pervious).
negprefix(a, unhappy, un, happy).
negprefix(a, undramatic, un, dramatic).
negprefix(a, acaudate, a, caudate).
negprefix(a, unavenged, un, avenged).
negprefix(a, unregretful, un, regretful).
negprefix(a, inadmissible, in, admissible).
negprefix(a, unveiled, un, veiled).
negprefix(a, unfortunate, un, fortunate).
negprefix(a, unsurprising, un, surprising).
negprefix(a, nonwoody, non, woody).
negprefix(a, unsaddled, un, saddled).
negprefix(a, inexperienced, in, experienced).
negprefix(a, impenetrable, im, penetrable).
negprefix(a, unpresidential, un, presidential).
negprefix(a, disinclined, dis, inclined).
negprefix(a, unloved, un, loved).
negprefix(a, unmotorized, un, motorized).
negprefix(a, unconstitutional, un, constitutional).
negprefix(a, unaddressed, un, addressed).
negprefix(a, noneffervescent, non, effervescent).
negprefix(a, inextricable, in, extricable).
negprefix(a, unaware, un, aware).
negprefix(a, incomparable, in, comparable).
negprefix(a, nonsuppurative, non, suppurative).
negprefix(a, anhydrous, an, hydrous).
negprefix(a, unreflected, un, reflected).
negprefix(a, invalid, in, valid).
negprefix(a, unalarming, un, alarming).
negprefix(a, unadjusted, un, adjusted).
negprefix(a, atypical, a, typical).
negprefix(a, abranchiate, a, branchiate).
negprefix(a, uncrystallized, un, crystallized).
negprefix(a, nonimitative, non, imitative).
negprefix(a, unseeded, un, seeded).
negprefix(a, illogical, il, logical).
negprefix(a, unweaned, un, weaned).
negprefix(a, unmodified, un, modified).
negprefix(a, improbable, im, probable).
negprefix(a, unresentful, un, resentful).
negprefix(a, nonprescription, non, prescription).
negprefix(a, irremovable, ir, removable).
negprefix(a, unpremeditated, un, premeditated).
negprefix(a, undiscerning, un, discerning).
negprefix(a, unacquisitive, un, acquisitive).
negprefix(a, nonrandom, non, random).
negprefix(a, uncoated, un, coated).
negprefix(a, unbalconied, un, balconied).
negprefix(a, unconvincing, un, convincing).
negprefix(a, nontechnical, non, technical).
negprefix(a, untucked, un, tucked).
negprefix(a, inviolable, in, violable).
negprefix(a, unpublished, un, published).
negprefix(a, ungenerous, un, generous).
negprefix(a, unsupportive, un, supportive).
negprefix(a, avascular, a, vascular).
negprefix(a, unwary, un, wary).
negprefix(a, disorienting, dis, orienting).
negprefix(a, invariable, in, variable).
negprefix(a, uncharacteristic, un, characteristic).
negprefix(a, avirulent, a, virulent).
negprefix(a, unheaded, un, headed).
negprefix(a, nonspatial, non, spatial).
negprefix(a, illegible, il, legible).
negprefix(a, unreassuring, un, reassuring).
negprefix(a, invertebrate, in, vertebrate).
negprefix(a, unquestionable, un, questionable).
negprefix(a, insubordinate, in, subordinate).
negprefix(a, unaccustomed, un, accustomed).
negprefix(a, uncontaminated, un, contaminated).
negprefix(a, unrestrained, un, restrained).
negprefix(a, unchangeable, un, changeable).
negprefix(a, unselfish, un, selfish).
negprefix(a, unserviceable, un, serviceable).
negprefix(a, unpalatable, un, palatable).
negprefix(a, unseamanlike, un, seamanlike).
negprefix(a, indeterminate, in, determinate).
negprefix(a, unmated, un, mated).
negprefix(a, immobile, im, mobile).
negprefix(a, inaccurate, in, accurate).
negprefix(a, inflexible, in, flexible).
negprefix(a, irreplaceable, ir, replaceable).
negprefix(a, unalert, un, alert).
negprefix(a, undelineated, un, delineated).
negprefix(a, nonaligned, non, aligned).
negprefix(a, intemperate, in, temperate).
negprefix(a, unarmored, un, armored).
negprefix(a, incompressible, in, compressible).
negprefix(a, unwaxed, un, waxed).
negprefix(a, incomplete, in, complete).
negprefix(a, nonhuman, non, human).
negprefix(a, unpaintable, un, paintable).
negprefix(a, unfastened, un, fastened).
negprefix(a, immoral, im, moral).
negprefix(a, inconsiderate, in, considerate).
negprefix(a, incommensurate, in, commensurate).
negprefix(a, unscholarly, un, scholarly).
negprefix(a, unblended, un, blended).
negprefix(a, uncreative, un, creative).
negprefix(a, immodest, im, modest).
negprefix(a, inglorious, in, glorious).
negprefix(a, unbridgeable, un, bridgeable).
negprefix(a, incompetent, in, competent).
negprefix(a, uninsured, un, insured).
negprefix(a, impersonal, im, personal).
negprefix(a, unmade, un, made).
negprefix(a, improvident, im, provident).
negprefix(a, unprocessed, un, processed).
negprefix(a, unreactive, un, reactive).
negprefix(a, noncombinative, non, combinative).
negprefix(a, unorganized, un, organized).
negprefix(a, incorrect, in, correct).
negprefix(a, involuntary, in, voluntary).
negprefix(a, nonmigratory, non, migratory).
negprefix(a, unenlivened, un, enlivened).
negprefix(a, unportable, un, portable).
negprefix(a, unwholesome, un, wholesome).
negprefix(a, unpublishable, un, publishable).
negprefix(a, unprophetic, un, prophetic).
negprefix(a, unexportable, un, exportable).
negprefix(a, nonpregnant, non, pregnant).
negprefix(a, unimpressive, un, impressive).
negprefix(a, nonarbitrary, non, arbitrary).
negprefix(a, noninvasive, non, invasive).
negprefix(a, unoccupied, un, occupied).
negprefix(a, unsociable, un, sociable).
negprefix(a, unconquerable, un, conquerable).
negprefix(a, unexpendable, un, expendable).
negprefix(a, inexhaustible, in, exhaustible).
negprefix(a, noninstitutionalized, non, institutionalized).
negprefix(a, uncarved, un, carved).
negprefix(a, disloyal, dis, loyal).
negprefix(a, incongruous, in, congruous).
negprefix(a, irreducible, ir, reducible).
negprefix(a, unprepared, un, prepared).
negprefix(a, nonarbitrable, non, arbitrable).
negprefix(a, unorthodox, un, orthodox).
negprefix(a, impalpable, im, palpable).
negprefix(a, unparented, un, parented).
negprefix(a, inevitable, in, evitable).
negprefix(a, unbarreled, un, barreled).
negprefix(a, unconditional, un, conditional).
negprefix(a, unpretentious, un, pretentious).
negprefix(a, unstaged, un, staged).
negprefix(a, inelegant, in, elegant).
negprefix(a, unaggressive, un, aggressive).
negprefix(a, nonvolatile, non, volatile).
negprefix(a, independent, in, dependent).
negprefix(a, unreportable, un, reportable).
negprefix(a, unsympathetic, un, sympathetic).
negprefix(a, unconstricted, un, constricted).
negprefix(a, disorderly, dis, orderly).
negprefix(a, unseasonable, un, seasonable).
negprefix(a, impolite, im, polite).
negprefix(a, unassisted, un, assisted).
negprefix(a, nondisposable, non, disposable).
negprefix(a, indefinite, in, definite).
negprefix(a, impermanent, im, permanent).
negprefix(a, unenlightened, un, enlightened).
negprefix(a, illiterate, il, literate).
negprefix(a, unsensational, un, sensational).
negprefix(a, nonintellectual, non, intellectual).
negprefix(a, unacknowledged, un, acknowledged).
negprefix(a, undemanding, un, demanding).
negprefix(a, unenclosed, un, enclosed).
negprefix(a, unsilenced, un, silenced).
negprefix(a, inadequate, in, adequate).
negprefix(a, unextended, un, extended).
negprefix(a, uninhibited, un, inhibited).
negprefix(a, unjust, un, just).
negprefix(a, undrinkable, un, drinkable).
negprefix(a, unfree, un, free).
negprefix(a, unrestricted, un, restricted).
negprefix(a, nonexempt, non, exempt).
negprefix(a, nonexecutive, non, executive).
negprefix(a, uncomfortable, un, comfortable).
negprefix(a, unconfined, un, confined).
negprefix(a, discontinued, dis, continued).
negprefix(a, unclassified, un, classified).
negprefix(a, unrealistic, un, realistic).
negprefix(a, unsold, un, sold).
negprefix(a, asynchronous, a, synchronous).
negprefix(a, unalterable, un, alterable).
negprefix(a, unattached, un, attached).
negprefix(a, unsusceptible, un, susceptible).
negprefix(a, nonporous, non, porous).
negprefix(a, untanned, un, tanned).
negprefix(a, unstained, un, stained).
negprefix(a, unshrinkable, un, shrinkable).
negprefix(a, incalculable, in, calculable).
negprefix(a, unstratified, un, stratified).
negprefix(a, unawakened, un, awakened).
negprefix(a, unconditioned, un, conditioned).
negprefix(a, nontraditional, non, traditional).
negprefix(a, unqualified, un, qualified).
negprefix(a, uninspiring, un, inspiring).
negprefix(a, ineffective, in, effective).
negprefix(a, unpleasant, un, pleasant).
negprefix(a, achromatinic, a, chromatinic).
negprefix(a, unseaworthy, un, seaworthy).
negprefix(a, unappendaged, un, appendaged).
negprefix(a, immortal, im, mortal).
negprefix(a, unapologetic, un, apologetic).
negprefix(a, nonfunctional, non, functional).
negprefix(a, insurmountable, in, surmountable).
negprefix(a, unconcerned, un, concerned).
negprefix(a, invulnerable, in, vulnerable).
negprefix(a, ungeared, un, geared).
negprefix(a, unconsummated, un, consummated).
negprefix(a, unpaved, un, paved).
negprefix(a, unobstructed, un, obstructed).
negprefix(a, unfathomable, un, fathomable).
negprefix(a, unforgettable, un, forgettable).
negprefix(a, unplayful, un, playful).
negprefix(a, unreliable, un, reliable).
negprefix(a, nonfictional, non, fictional).
negprefix(a, uncompartmented, un, compartmented).
negprefix(a, disenfranchised, dis, enfranchised).
negprefix(a, unusual, un, usual).
negprefix(a, unhurried, un, hurried).
negprefix(a, uncertified, un, certified).
negprefix(a, unnecessary, un, necessary).
negprefix(a, unlike, un, like).
negprefix(a, untangled, un, tangled).
negprefix(a, aplacental, a, placental).
negprefix(a, unearned, un, earned).
negprefix(a, unlivable, un, livable).
negprefix(a, unlighted, un, lighted).
negprefix(a, unsupported, un, supported).
negprefix(a, unexciting, un, exciting).
negprefix(a, unobtrusive, un, obtrusive).
negprefix(a, undrained, un, drained).
negprefix(a, unleavened, un, leavened).
negprefix(a, insincere, in, sincere).
negprefix(a, incapable, in, capable).
negprefix(a, unintended, un, intended).
negprefix(a, untied, un, tied).
negprefix(a, nonslippery, non, slippery).
negprefix(a, unrewarding, un, rewarding).
negprefix(a, uninjectable, un, injectable).
negprefix(a, inconvertible, in, convertible).
negprefix(a, insignificant, in, significant).
negprefix(a, unmalted, un, malted).
negprefix(a, nonmagnetic, non, magnetic).
negprefix(a, unmalicious, un, malicious).
negprefix(a, unrentable, un, rentable).
negprefix(a, inconspicuous, in, conspicuous).
negprefix(a, imponderable, im, ponderable).
negprefix(a, immoderate, im, moderate).
negprefix(a, nonterritorial, non, territorial).
negprefix(a, acyclic, a, cyclic).
negprefix(a, afebrile, a, febrile).
negprefix(a, indiscernible, in, discernible).
negprefix(a, uncontested, un, contested).
negprefix(a, noncommercial, non, commercial).
negprefix(a, unabused, un, abused).
negprefix(a, unintelligent, un, intelligent).
negprefix(a, uncut, un, cut).
negprefix(a, discomposed, dis, composed).
negprefix(a, incontinent, in, continent).
negprefix(a, unbordered, un, bordered).
negprefix(a, insatiate, in, satiate).
negprefix(a, indefeasible, in, defeasible).
negprefix(a, implacable, im, placable).
negprefix(a, unblemished, un, blemished).
negprefix(a, imprecise, im, precise).
negprefix(a, inequitable, in, equitable).
negprefix(a, impatient, im, patient).
negprefix(a, unsocial, un, social).
negprefix(a, uncivil, un, civil).
negprefix(a, impotent, im, potent).
negprefix(a, unaccommodating, un, accommodating).
negprefix(a, undiplomatic, un, diplomatic).
negprefix(a, unmodifiable, un, modifiable).
negprefix(a, unfavorable, un, favorable).
negprefix(a, unbreakable, un, breakable).
negprefix(a, indeterminable, in, determinable).
negprefix(a, inexact, in, exact).
negprefix(a, unwooded, un, wooded).
negprefix(a, incommodious, in, commodious).
negprefix(a, uncontroversial, un, controversial).
negprefix(a, unretentive, un, retentive).
negprefix(a, unwearable, un, wearable).
negprefix(a, infinite, in, finite).
negprefix(a, disproportionate, dis, proportionate).
negprefix(a, unwebbed, un, webbed).
negprefix(a, unholy, un, holy).
negprefix(a, unangry, un, angry).
negprefix(a, unconstipated, un, constipated).
negprefix(a, inconsiderable, in, considerable).
negprefix(a, unrenewable, un, renewable).
negprefix(a, unashamed, un, ashamed).
negprefix(a, nonradioactive, non, radioactive).
negprefix(a, unmarked, un, marked).
negprefix(a, unrefined, un, refined).
negprefix(a, unopposable, un, opposable).
negprefix(a, illegitimate, il, legitimate).
negprefix(a, nonspecific, non, specific).
negprefix(a, unappetizing, un, appetizing).
negprefix(a, informal, in, formal).
negprefix(a, uninfluential, un, influential).
negprefix(a, unauthorized, un, authorized).
negprefix(a, irreligious, ir, religious).
negprefix(a, nonsteroidal, non, steroidal).
negprefix(a, nonexistent, non, existent).
negprefix(a, nonretractile, non, retractile).
negprefix(a, ametabolic, a, metabolic).
negprefix(a, unrhymed, un, rhymed).
negprefix(a, unpronounceable, un, pronounceable).
negprefix(a, unfriendly, un, friendly).
negprefix(a, nonclassical, non, classical).
negprefix(a, undesigned, un, designed).
negprefix(a, anaerobic, an, aerobic).
negprefix(a, nonreturnable, non, returnable).
negprefix(a, unrelated, un, related).
negprefix(a, disorganized, dis, organized).
negprefix(a, unprincipled, un, principled).
negprefix(a, unstudied, un, studied).
negprefix(a, unswept, un, swept).
negprefix(a, unreproducible, un, reproducible).
negprefix(a, noncrystalline, non, crystalline).
negprefix(a, uncomplimentary, un, complimentary).
negprefix(a, unsatisfactory, un, satisfactory).
negprefix(a, unreal, un, real).
negprefix(a, nonexplosive, non, explosive).
negprefix(a, unobligated, un, obligated).
negprefix(a, ungusseted, un, gusseted).
negprefix(a, incorporeal, in, corporeal).
negprefix(a, unbuttoned, un, buttoned).
negprefix(a, unappealing, un, appealing).
negprefix(a, nonresident, non, resident).
negprefix(a, unpermissive, un, permissive).
negprefix(a, nonrepetitive, non, repetitive).
negprefix(a, unacceptable, un, acceptable).
negprefix(a, unpreventable, un, preventable).
negprefix(a, undiscriminating, un, discriminating).
negprefix(a, nonfinancial, non, financial).
negprefix(a, undemocratic, un, democratic).
negprefix(a, unknown, un, known).
negprefix(a, inclement, in, clement).
negprefix(a, unmanned, un, manned).
negprefix(a, inexpedient, in, expedient).
negprefix(a, nonsyllabic, non, syllabic).
negprefix(a, inelastic, in, elastic).
negprefix(a, disobedient, dis, obedient).
negprefix(a, disingenuous, dis, ingenuous).
negprefix(a, unmindful, un, mindful).
negprefix(a, unsoured, un, soured).
negprefix(a, undimmed, un, dimmed).
negprefix(a, unemployable, un, employable).
negprefix(a, nonmetamorphic, non, metamorphic).
negprefix(a, ineradicable, in, eradicable).
negprefix(a, nonintegrated, non, integrated).
negprefix(a, unanalyzed, un, analyzed).
negprefix(a, unexcited, un, excited).
negprefix(a, indiscriminate, in, discriminate).
negprefix(a, unformed, un, formed).
negprefix(a, unrepentant, un, repentant).
negprefix(a, distrustful, dis, trustful).
negprefix(a, unstimulating, un, stimulating).
negprefix(a, unequipped, un, equipped).
negprefix(a, indistinguishable, in, distinguishable).
negprefix(a, impractical, im, practical).
negprefix(a, immeasurable, im, measurable).
negprefix(a, unpredictable, un, predictable).
negprefix(a, nonreflective, non, reflective).
negprefix(a, unfrozen, un, frozen).
negprefix(a, unbanded, un, banded).
negprefix(a, unalike, un, alike).
negprefix(a, unmilitary, un, military).
negprefix(a, unventilated, un, ventilated).
negprefix(a, unpeaceful, un, peaceful).
negprefix(a, unavailable, un, available).
negprefix(a, unsuspected, un, suspected).
negprefix(a, unsaponified, un, saponified).
negprefix(a, unpatriotic, un, patriotic).
negprefix(a, underived, un, derived).
negprefix(a, unsanitary, un, sanitary).
negprefix(a, unarmed, un, armed).
negprefix(a, unquotable, un, quotable).
negprefix(a, unactable, un, actable).
negprefix(a, unsalable, un, salable).
negprefix(a, unstressed, un, stressed).
negprefix(a, unwrinkled, un, wrinkled).
negprefix(a, unreceptive, un, receptive).
negprefix(a, indirect, in, direct).
negprefix(a, aperiodic, a, periodic).
negprefix(a, nonpsychoactive, non, psychoactive).
negprefix(a, unquiet, un, quiet).
negprefix(a, unmyelinated, un, myelinated).
negprefix(a, unimproved, un, improved).
negprefix(a, unlamented, un, lamented).
negprefix(a, unmerited, un, merited).
negprefix(a, nonviolent, non, violent).
negprefix(a, unambiguous, un, ambiguous).
negprefix(a, unsuccessful, un, successful).
negprefix(a, unowned, un, owned).
negprefix(a, uncommon, un, common).
negprefix(a, impossible, im, possible).
negprefix(a, unscrupulous, un, scrupulous).
negprefix(a, nonadhesive, non, adhesive).
negprefix(a, anestrous, an, estrous).
negprefix(a, unimpressionable, un, impressionable).
negprefix(a, undetected, un, detected).
negprefix(a, nonconformist, non, conformist).
negprefix(a, undifferentiated, un, differentiated).
negprefix(a, unassigned, un, assigned).
negprefix(a, noncrucial, non, crucial).
negprefix(a, unshaven, un, shaven).
negprefix(a, undiversified, un, diversified).
negprefix(a, inedible, in, edible).
negprefix(a, unlimited, un, limited).
negprefix(a, unsigned, un, signed).
negprefix(a, nonsurgical, non, surgical).
negprefix(a, unchartered, un, chartered).
negprefix(a, unnoticed, un, noticed).
negprefix(a, irresistible, ir, resistible).
negprefix(a, noncomprehensive, non, comprehensive).
negprefix(a, unperplexed, un, perplexed).
negprefix(a, unfastidious, un, fastidious).
negprefix(a, inadvisable, in, advisable).
negprefix(a, unattributable, un, attributable).
negprefix(a, incongruent, in, congruent).
negprefix(a, unposed, un, posed).
negprefix(a, unguided, un, guided).
negprefix(a, unidentifiable, un, identifiable).
negprefix(a, indehiscent, in, dehiscent).
negprefix(a, inconsistent, in, consistent).
negprefix(a, uncrannied, un, crannied).
negprefix(a, ungroomed, un, groomed).
negprefix(a, nonarboreal, non, arboreal).
negprefix(a, unpowered, un, powered).
negprefix(a, nonaddictive, non, addictive).
negprefix(a, unfashionable, un, fashionable).
negprefix(a, unkind, un, kind).
negprefix(a, imprudent, im, prudent).
negprefix(a, incoherent, in, coherent).
negprefix(a, anisotropic, an, isotropic).
negprefix(a, atonic, a, tonic).
negprefix(a, unmotivated, un, motivated).
negprefix(a, uninflected, un, inflected).
negprefix(a, nonmoving, non, moving).
negprefix(a, disrespectful, dis, respectful).
negprefix(a, noncompetitive, non, competitive).
negprefix(a, undeclared, un, declared).
negprefix(a, discourteous, dis, courteous).
negprefix(a, nonwashable, non, washable).
negprefix(a, intangible, in, tangible).
negprefix(a, nonrigid, non, rigid).
negprefix(a, insensible, in, sensible).
negprefix(a, unforgiving, un, forgiving).
negprefix(a, disagreeable, dis, agreeable).
negprefix(a, unresponsive, un, responsive).
negprefix(a, agnostic, a, gnostic).
negprefix(a, undescriptive, un, descriptive).
negprefix(a, unenterprising, un, enterprising).
negprefix(a, uncrowded, un, crowded).
negprefix(a, ungregarious, un, gregarious).
negprefix(a, unappealable, un, appealable).
negprefix(a, incurable, in, curable).
negprefix(a, unlisted, un, listed).
negprefix(a, uninstructive, un, instructive).
negprefix(a, unvoiced, un, voiced).
negprefix(a, uncensored, un, censored).
negprefix(a, undiluted, un, diluted).
negprefix(a, unfilled, un, filled).
negprefix(a, nonionized, non, ionized).
negprefix(a, irreparable, ir, reparable).
negprefix(a, unlined, un, lined).
negprefix(a, inexplicable, in, explicable).
negprefix(a, unconnected, un, connected).

negprefix(r, invisibly, in, visibly).
negprefix(r, unkindly, un, kindly).
negprefix(r, improperly, im, properly).
negprefix(r, injudiciously, in, judiciously).
negprefix(r, insufficiently, in, sufficiently).
negprefix(r, informally, in, formally).
negprefix(r, imperceptibly, im, perceptibly).
negprefix(r, unsentimentally, un, sentimentally).
negprefix(r, ineffectively, in, effectively).
negprefix(r, unromantically, un, romantically).
negprefix(r, infelicitously, in, felicitously).
negprefix(r, dishonestly, dis, honestly).
negprefix(r, unjustly, un, justly).
negprefix(r, unwittingly, un, wittingly).
negprefix(r, insanely, in, sanely).
negprefix(r, immeasurably, im, measurably).
negprefix(r, unforgivably, un, forgivably).
negprefix(r, ungrudgingly, un, grudgingly).
negprefix(r, disproportionately, dis, proportionately).
negprefix(r, unhygienically, un, hygienically).
negprefix(r, unreliably, un, reliably).
negprefix(r, nonviolently, non, violently).
negprefix(r, illicitly, il, licitly).
negprefix(r, ungraciously, un, graciously).
negprefix(r, unsmilingly, un, smilingly).
negprefix(r, unbelievably, un, believably).
negprefix(r, unemotionally, un, emotionally).
negprefix(r, uncomfortably, un, comfortably).
negprefix(r, unashamedly, un, ashamedly).
negprefix(r, unenthusiastically, un, enthusiastically).
negprefix(r, inhumanely, in, humanely).
negprefix(r, inhospitably, in, hospitably).
negprefix(r, imprecisely, im, precisely).
negprefix(r, indecisively, in, decisively).
negprefix(r, unhelpfully, un, helpfully).
negprefix(r, infrequently, in, frequently).
negprefix(r, unprecedentedly, un, precedentedly).
negprefix(r, uninformatively, un, informatively).
negprefix(r, inconveniently, in, conveniently).
negprefix(r, disapprovingly, dis, approvingly).
negprefix(r, unpalatably, un, palatably).
negprefix(r, asymmetrically, a, symmetrically).
negprefix(r, imperfectly, im, perfectly).
negprefix(r, uninstructively, un, instructively).
negprefix(r, indecorously, in, decorously).
negprefix(r, insecurely, in, securely).
negprefix(r, unequally, un, equally).
negprefix(r, unrealistically, un, realistically).
negprefix(r, inoffensively, in, offensively).
negprefix(r, irrelevantly, ir, relevantly).
negprefix(r, unsatisfactorily, un, satisfactorily).
negprefix(r, unintentionally, un, intentionally).
negprefix(r, unchivalrously, un, chivalrously).
negprefix(r, ungracefully, un, gracefully).
negprefix(r, unfortunately, un, fortunately).
negprefix(r, unassertively, un, assertively).
negprefix(r, incomparably, in, comparably).
negprefix(r, inappropriately, in, appropriately).
negprefix(r, unreasonably, un, reasonably).
negprefix(r, insignificantly, in, significantly).
negprefix(r, irreverently, ir, reverently).
negprefix(r, inadvertently, in, advertently).
negprefix(r, unfaithfully, un, faithfully).
negprefix(r, insensitively, in, sensitively).
negprefix(r, unfeelingly, un, feelingly).
negprefix(r, illegibly, il, legibly).
negprefix(r, incorrectly, in, correctly).
negprefix(r, uncontroversially, un, controversially).
negprefix(r, unfashionably, un, fashionably).
negprefix(r, undemocratically, un, democratically).
negprefix(r, unimpressively, un, impressively).
negprefix(r, unconvincingly, un, convincingly).
negprefix(r, discourteously, dis, courteously).
negprefix(r, undiplomatically, un, diplomatically).
negprefix(r, intransitively, in, transitively).
negprefix(r, indirectly, in, directly).
negprefix(r, inopportunely, in, opportunely).
negprefix(r, immorally, im, morally).
negprefix(r, unnaturally, un, naturally).
negprefix(r, noncomprehensively, non, comprehensively).
negprefix(r, unethically, un, ethically).
negprefix(r, distrustfully, dis, trustfully).
negprefix(r, unofficially, un, officially).
negprefix(r, unforgivingly, un, forgivingly).
negprefix(r, unfavorably, un, favorably).
negprefix(r, disobediently, dis, obediently).
negprefix(r, unpropitiously, un, propitiously).
negprefix(r, inefficiently, in, efficiently).
negprefix(r, inconspicuously, in, conspicuously).
negprefix(r, unluckily, un, luckily).
negprefix(r, illegitimately, il, legitimately).
negprefix(r, impolitely, im, politely).
negprefix(r, unintelligently, un, intelligently).
negprefix(r, unmemorably, un, memorably).
negprefix(r, inaudibly, in, audibly).
negprefix(r, inexpediently, in, expediently).
negprefix(r, inexpressively, in, expressively).
negprefix(r, improvidently, im, providently).
negprefix(r, unappreciatively, un, appreciatively).
negprefix(r, unhappily, un, happily).
negprefix(r, illogically, il, logically).
negprefix(r, unintelligibly, un, intelligibly).
negprefix(r, immodestly, im, modestly).
negprefix(r, uncharacteristically, un, characteristically).
negprefix(r, unselfishly, un, selfishly).
negprefix(r, unpatriotically, un, patriotically).
negprefix(r, unproductively, un, productively).
negprefix(r, immaturely, im, maturely).
negprefix(r, unobtrusively, un, obtrusively).
negprefix(r, uninterestingly, un, interestingly).
negprefix(r, inflexibly, in, flexibly).
negprefix(r, disreputably, dis, reputably).
negprefix(r, unknowingly, un, knowingly).
negprefix(r, impenitently, im, penitently).
negprefix(r, unhurriedly, un, hurriedly).
negprefix(r, unmanfully, un, manfully).
negprefix(r, unmindfully, un, mindfully).
negprefix(r, ineffectually, in, effectually).
negprefix(r, unlawfully, un, lawfully).
negprefix(r, disloyally, dis, loyally).
negprefix(r, incompetently, in, competently).
negprefix(r, unseasonably, un, seasonably).
negprefix(r, unnecessarily, un, necessarily).
negprefix(r, unconventionally, un, conventionally).
negprefix(r, unwillingly, un, willingly).
negprefix(r, unacceptably, un, acceptably).
negprefix(r, inconsequentially, in, consequentially).
negprefix(r, unpretentiously, un, pretentiously).
negprefix(r, inconsiderately, in, considerately).
negprefix(r, unconstitutionally, un, constitutionally).
negprefix(r, impatiently, im, patiently).
negprefix(r, undependably, un, dependably).
negprefix(r, inconsistently, in, consistently).
negprefix(r, indiscreetly, in, discreetly).
negprefix(r, unremarkably, un, remarkably).
negprefix(r, irregularly, ir, regularly).
negprefix(r, ungratefully, un, gratefully).
negprefix(r, unrepentantly, un, repentantly).
negprefix(r, unsympathetically, un, sympathetically).
negprefix(r, imprudently, im, prudently).
negprefix(r, unsuitably, un, suitably).
negprefix(r, incompatibly, in, compatibly).
negprefix(r, unimaginatively, un, imaginatively).
negprefix(r, unsociably, un, sociably).
negprefix(r, unceremoniously, un, ceremoniously).
negprefix(r, undeservedly, un, deservedly).
negprefix(r, atypically, a, typically).
negprefix(r, inelegantly, in, elegantly).
negprefix(r, unmanageably, un, manageably).
negprefix(r, inaccurately, in, accurately).
negprefix(r, unambitiously, un, ambitiously).
negprefix(r, inorganically, in, organically).
negprefix(r, unfairly, un, fairly).
negprefix(r, ineloquently, in, eloquently).
negprefix(r, unjustifiably, un, justifiably).
negprefix(r, unmusically, un, musically).
negprefix(r, disagreeably, dis, agreeably).
negprefix(r, impossibly, im, possibly).
negprefix(r, unexcitingly, un, excitingly).
negprefix(r, insincerely, in, sincerely).
negprefix(r, uncivilly, un, civilly).
negprefix(r, inconclusively, in, conclusively).
negprefix(r, impersonally, im, personally).
negprefix(r, unsuccessfully, un, successfully).
negprefix(r, irrationally, ir, rationally).
negprefix(r, intolerably, in, tolerably).
negprefix(r, indecently, in, decently).
negprefix(r, unsteadily, un, steadily).
negprefix(r, unpardonably, un, pardonably).
negprefix(r, irresponsibly, ir, responsibly).
negprefix(r, irresolutely, ir, resolutely).
negprefix(r, unconditionally, un, conditionally).
negprefix(r, unrecognizably, un, recognizably).
negprefix(r, untruthfully, un, truthfully).
negprefix(r, inadequately, in, adequately).
negprefix(r, inarticulately, in, articulately).
negprefix(r, immoderately, im, moderately).
negprefix(r, ungrammatically, un, grammatically).
negprefix(r, unsportingly, un, sportingly).
negprefix(r, incredibly, in, credibly).
negprefix(r, noncompetitively, non, competitively).
negprefix(r, unquietly, un, quietly).
negprefix(r, inauspiciously, in, auspiciously).
negprefix(r, unrighteously, un, righteously).
negprefix(r, involuntarily, in, voluntarily).
negprefix(r, unattractively, un, attractively).
negprefix(r, unmelodiously, un, melodiously).
negprefix(r, incautiously, in, cautiously).
negprefix(r, unsystematically, un, systematically).
negprefix(r, inexcusably, in, excusably).
negprefix(r, inequitably, in, equitably).
negprefix(r, unwarily, un, warily).
negprefix(r, dishonorably, dis, honorably).
negprefix(r, disrespectfully, dis, respectfully).
negprefix(r, disadvantageously, dis, advantageously).
negprefix(r, incoherently, in, coherently).
negprefix(r, unambiguously, un, ambiguously).
negprefix(r, inefficaciously, in, efficaciously).
negprefix(r, unprofitably, un, profitably).
negprefix(r, unbelievingly, un, believingly).
negprefix(r, infinitely, in, finitely).
negprefix(r, unpleasantly, un, pleasantly).
negprefix(r, unconsciously, un, consciously).
negprefix(r, incredulously, in, credulously).
negprefix(r, inseparably, in, separably).
negprefix(r, inexactly, in, exactly).
negprefix(r, uncomplainingly, un, complainingly).
negprefix(r, impermissibly, im, permissibly).
negprefix(r, undramatically, un, dramatically).
negprefix(r, unappealingly, un, appealingly).
negprefix(r, uncritically, un, critically).
negprefix(r, unevenly, un, evenly).
negprefix(r, intolerantly, in, tolerantly).

negprefix(n, disarmament, dis, armament).
negprefix(n, inactiveness, in, activeness).
negprefix(n, illiberality, il, liberality).
negprefix(n, impracticality, im, practicality).
negprefix(n, unavailability, un, availability).
negprefix(n, unconscientiousness, un, conscientiousness).
negprefix(n, unpointedness, un, pointedness).
negprefix(n, impotence, im, potence).
negprefix(n, insubstantiality, in, substantiality).
negprefix(n, unsusceptibility, un, susceptibility).
negprefix(n, impossibility, im, possibility).
negprefix(n, disorder, dis, order).
negprefix(n, atonality, a, tonality).
negprefix(n, disapprobation, dis, approbation).
negprefix(n, incurableness, in, curableness).
negprefix(n, uninterestingness, un, interestingness).
negprefix(n, asynchronous_operation, a, synchronous_operation).
negprefix(n, indecency, in, decency).
negprefix(n, unorthodoxy, un, orthodoxy).
negprefix(n, disincentive, dis, incentive).
negprefix(n, distrust, dis, trust).
negprefix(n, irreverence, ir, reverence).
negprefix(n, incredibility, in, credibility).
negprefix(n, incompleteness, in, completeness).
negprefix(n, impenetrability, im, penetrability).
negprefix(n, unwariness, un, wariness).
negprefix(n, unfavorableness, un, favorableness).
negprefix(n, untruthfulness, un, truthfulness).
negprefix(n, impurity, im, purity).
negprefix(n, indispensability, in, dispensability).
negprefix(n, inadmissibility, in, admissibility).
negprefix(n, 'non-market_economy', 'non-', market_economy).
negprefix(n, unfairness, un, fairness).
negprefix(n, inconsideration, in, consideration).
negprefix(n, nonsmoker, non, smoker).
negprefix(n, nonconformism, non, conformism).
negprefix(n, immoderation, im, moderation).
negprefix(n, irreversibility, ir, reversibility).
negprefix(n, inaptness, in, aptness).
negprefix(n, ingratitude, in, gratitude).
negprefix(n, imprecision, im, precision).
negprefix(n, invariableness, in, variableness).
negprefix(n, unconventionality, un, conventionality).
negprefix(n, discourtesy, dis, courtesy).
negprefix(n, irresoluteness, ir, resoluteness).
negprefix(n, unhealthfulness, un, healthfulness).
negprefix(n, indispensableness, in, dispensableness).
negprefix(n, atypicality, a, typicality).
negprefix(n, dishonorableness, dis, honorableness).
negprefix(n, incapacity, in, capacity).
negprefix(n, dishonor, dis, honor).
negprefix(n, insecurity, in, security).
negprefix(n, unconcern, un, concern).
negprefix(n, inexperience, in, experience).
negprefix(n, inhospitality, in, hospitality).
negprefix(n, nonattendance, non, attendance).
negprefix(n, invulnerability, in, vulnerability).
negprefix(n, disrepute, dis, repute).
negprefix(n, discomposure, dis, composure).
negprefix(n, unattractiveness, un, attractiveness).
negprefix(n, unacceptability, un, acceptability).
negprefix(n, incomprehension, in, comprehension).
negprefix(n, unaffectedness, un, affectedness).
negprefix(n, nonpayment, non, payment).
negprefix(n, inutility, in, utility).
negprefix(n, unpopularity, un, popularity).
negprefix(n, nonvolatile_storage, non, volatile_storage).
negprefix(n, impermeability, im, permeability).
negprefix(n, insincerity, in, sincerity).
negprefix(n, impropriety, im, propriety).
negprefix(n, improvidence, im, providence).
negprefix(n, nonpartisan, non, partisan).
negprefix(n, inefficacy, in, efficacy).
negprefix(n, impreciseness, im, preciseness).
negprefix(n, indiscipline, in, discipline).
negprefix(n, unthoughtfulness, un, thoughtfulness).
negprefix(n, astigmatism, a, stigmatism).
negprefix(n, impoliteness, im, politeness).
negprefix(n, illogicality, il, logicality).
negprefix(n, unrighteousness, un, righteousness).
negprefix(n, unlisted_security, un, listed_security).
negprefix(n, incorruptibility, in, corruptibility).
negprefix(n, inexpensiveness, in, expensiveness).
negprefix(n, unmalleability, un, malleability).
negprefix(n, unpermissiveness, un, permissiveness).
negprefix(n, unearned_run, un, earned_run).
negprefix(n, unconnectedness, un, connectedness).
negprefix(n, anaphrodisia, an, aphrodisia).
negprefix(n, nonintervention, non, intervention).
negprefix(n, impracticableness, im, practicableness).
negprefix(n, disarming, dis, arming).
negprefix(n, unskillfulness, un, skillfulness).
negprefix(n, uncertainty, un, certainty).
negprefix(n, unselfishness, un, selfishness).
negprefix(n, inaction, in, action).
negprefix(n, inadvisability, in, advisability).
negprefix(n, unlikeness, un, likeness).
negprefix(n, uncreativeness, un, creativeness).
negprefix(n, insalubrity, in, salubrity).
negprefix(n, inefficiency, in, efficiency).
negprefix(n, imperviousness, im, perviousness).
negprefix(n, unlikeliness, un, likeliness).
negprefix(n, inaccuracy, in, accuracy).
negprefix(n, nondriver, non, driver).
negprefix(n, inconspicuousness, in, conspicuousness).
negprefix(n, unwholesomeness, un, wholesomeness).
negprefix(n, undependableness, un, dependableness).
negprefix(n, insentience, in, sentience).
negprefix(n, insalubriousness, in, salubriousness).
negprefix(n, nonparticipation, non, participation).
negprefix(n, insignificance, in, significance).
negprefix(n, unprofitability, un, profitability).
negprefix(n, impalpability, im, palpability).
negprefix(n, incorporeality, in, corporeality).
negprefix(n, unmindfulness, un, mindfulness).
negprefix(n, unneighborliness, un, neighborliness).
negprefix(n, incognizance, in, cognizance).
negprefix(n, anestrus, an, estrus).
negprefix(n, disassociation, dis, association).
negprefix(n, nonequivalence, non, equivalence).
negprefix(n, incorruptness, in, corruptness).
negprefix(n, nonconformist, non, conformist).
negprefix(n, invariability, in, variability).
negprefix(n, uncleanliness, un, cleanliness).
negprefix(n, disloyalty, dis, loyalty).
negprefix(n, noncitizen, non, citizen).
negprefix(n, insolubility, in, solubility).
negprefix(n, infallibility, in, fallibility).
negprefix(n, unstratified_language, un, stratified_language).
negprefix(n, unpleasingness, un, pleasingness).
negprefix(n, inessentiality, in, essentiality).
negprefix(n, inessential, in, essential).
negprefix(n, inflexibility, in, flexibility).
negprefix(n, intolerance, in, tolerance).
negprefix(n, uninsurability, un, insurability).
negprefix(n, 'non-proliferation', 'non-', proliferation).
negprefix(n, unlikelihood, un, likelihood).
negprefix(n, unhappiness, un, happiness).
negprefix(n, inadequacy, in, adequacy).
negprefix(n, inconclusiveness, in, conclusiveness).
negprefix(n, nonmember, non, member).
negprefix(n, untimeliness, un, timeliness).
negprefix(n, untidiness, un, tidiness).
negprefix(n, unclearness, un, clearness).
negprefix(n, unresponsiveness, un, responsiveness).
negprefix(n, ungodliness, un, godliness).
negprefix(n, irresponsibility, ir, responsibility).
negprefix(n, inelasticity, in, elasticity).
negprefix(n, illegitimacy, il, legitimacy).
negprefix(n, injustice, in, justice).
negprefix(n, indestructibility, in, destructibility).
negprefix(n, unexpectedness, un, expectedness).
negprefix(n, immediacy, im, mediacy).
negprefix(n, nonobservance, non, observance).
negprefix(n, unseasonableness, un, seasonableness).
negprefix(n, imperfection, im, perfection).
negprefix(n, untrustiness, un, trustiness).
negprefix(n, nonworker, non, worker).
negprefix(n, uncheerfulness, un, cheerfulness).
negprefix(n, indecisiveness, in, decisiveness).
negprefix(n, nonexistence, non, existence).
negprefix(n, inexpediency, in, expediency).
negprefix(n, indigestibility, in, digestibility).
negprefix(n, inexplicitness, in, explicitness).
negprefix(n, inauspiciousness, in, auspiciousness).
negprefix(n, incompressibility, in, compressibility).
negprefix(n, incapability, in, capability).
negprefix(n, indistinctness, in, distinctness).
negprefix(n, nondevelopment, non, development).
negprefix(n, untrustworthiness, un, trustworthiness).
negprefix(n, incompatibility, in, compatibility).
negprefix(n, improbability, im, probability).
negprefix(n, illegality, il, legality).
negprefix(n, illiteracy, il, literacy).
negprefix(n, impracticability, im, practicability).
negprefix(n, incoordination, in, coordination).
negprefix(n, unambiguity, un, ambiguity).
negprefix(n, unlawfulness, un, lawfulness).
negprefix(n, insensitiveness, in, sensitiveness).
negprefix(n, unperceptiveness, un, perceptiveness).
negprefix(n, inexpedience, in, expedience).
negprefix(n, improperness, im, properness).
negprefix(n, impiety, im, piety).
negprefix(n, asymmetry, a, symmetry).
negprefix(n, inattentiveness, in, attentiveness).
negprefix(n, inapplicability, in, applicability).
negprefix(n, irreversible_process, ir, reversible_process).
negprefix(n, disagreement, dis, agreement).
negprefix(n, imperfectibility, im, perfectibility).
negprefix(n, unreliability, un, reliability).
negprefix(n, disapproval, dis, approval).
negprefix(n, inability, in, ability).
negprefix(n, unevenness, un, evenness).
negprefix(n, nonbeing, non, being).
negprefix(n, inattention, in, attention).
negprefix(n, 'non-involvement', 'non-', involvement).
negprefix(n, noninterference, non, interference).
negprefix(n, incorrectness, in, correctness).
negprefix(n, intemperance, in, temperance).
negprefix(n, impartiality, im, partiality).
negprefix(n, incurability, in, curability).
negprefix(n, immateriality, im, materiality).
negprefix(n, unnaturalness, un, naturalness).
negprefix(n, unemotionality, un, emotionality).
negprefix(n, unsociability, un, sociability).
negprefix(n, uncongeniality, un, congeniality).
negprefix(n, unscrupulousness, un, scrupulousness).
negprefix(n, immutability, im, mutability).
negprefix(n, uninitiate, un, initiate).
negprefix(n, inappropriateness, in, appropriateness).
negprefix(n, disingenuousness, dis, ingenuousness).
negprefix(n, unsatisfactoriness, un, satisfactoriness).
negprefix(n, disembarkation, dis, embarkation).
negprefix(n, disinclination, dis, inclination).
negprefix(n, disembarrassment, dis, embarrassment).
negprefix(n, impatience, im, patience).
negprefix(n, intransitivity, in, transitivity).
negprefix(n, immovability, im, movability).
negprefix(n, disproportion, dis, proportion).
negprefix(n, unwillingness, un, willingness).
negprefix(n, informality, in, formality).
negprefix(n, implausibility, im, plausibility).
negprefix(n, discontinuity, dis, continuity).
negprefix(n, disrespect, dis, respect).
negprefix(n, 'non-volatile_storage', 'non-', volatile_storage).
negprefix(n, impermanence, im, permanence).
negprefix(n, insanity, in, sanity).
negprefix(n, unceremoniousness, un, ceremoniousness).
negprefix(n, nonreligious_person, non, religious_person).
negprefix(n, unfaithfulness, un, faithfulness).
negprefix(n, atonicity, a, tonicity).
negprefix(n, unpleasantness, un, pleasantness).
negprefix(n, unrestraint, un, restraint).
negprefix(n, disagreeableness, dis, agreeableness).
negprefix(n, unsteadiness, un, steadiness).
negprefix(n, unprofitableness, un, profitableness).
negprefix(n, incoherence, in, coherence).
negprefix(n, inexactness, in, exactness).
negprefix(n, dissimilarity, dis, similarity).
negprefix(n, unleaded_gasoline, un, leaded_gasoline).
negprefix(n, unpropitiousness, un, propitiousness).
negprefix(n, nonbiodegradable_pollution, non, biodegradable_pollution).
negprefix(n, infiniteness, in, finiteness).
negprefix(n, imprudence, im, prudence).
negprefix(n, ineffectiveness, in, effectiveness).
negprefix(n, 'non-engagement', 'non-', engagement).
negprefix(n, unfriendliness, un, friendliness).
negprefix(n, immorality, im, morality).
negprefix(n, disadvantage, dis, advantage).
negprefix(n, unoriginality, un, originality).
negprefix(n, asynchronism, a, synchronism).
negprefix(n, inaptitude, in, aptitude).
negprefix(n, nonsingular_matrix, non, singular_matrix).
negprefix(n, imperceptibility, im, perceptibility).
negprefix(n, unwellness, un, wellness).
negprefix(n, incomprehensibility, in, comprehensibility).
negprefix(n, disunion, dis, union).
negprefix(n, unintelligibility, un, intelligibility).
negprefix(n, immobility, im, mobility).
negprefix(n, discontinuation, dis, continuation).
negprefix(n, inconsistency, in, consistency).
negprefix(n, indirect_discourse, in, direct_discourse).
negprefix(n, insufficiency, in, sufficiency).
negprefix(n, unbreakableness, un, breakableness).
negprefix(n, insecureness, in, secureness).
negprefix(n, dissatisfaction, dis, satisfaction).
negprefix(n, unbecomingness, un, becomingness).
negprefix(n, discomfort, dis, comfort).
negprefix(n, immaturity, im, maturity).
negprefix(n, immodesty, im, modesty).
negprefix(n, unkindness, un, kindness).
negprefix(n, incivility, in, civility).
negprefix(n, anovulation, an, ovulation).
negprefix(n, impermissibility, im, permissibility).
negprefix(n, unpredictability, un, predictability).
negprefix(n, unsanitariness, un, sanitariness).
negprefix(n, unworthiness, un, worthiness).
negprefix(n, uncommunicativeness, un, communicativeness).
negprefix(n, nonresident, non, resident).
negprefix(n, unsecured_bond, un, secured_bond).
negprefix(n, inaudibility, in, audibility).
negprefix(n, dishonesty, dis, honesty).
negprefix(n, illegibility, il, legibility).
negprefix(n, unusualness, un, usualness).
negprefix(n, instability, in, stability).
negprefix(n, unsoundness, un, soundness).
negprefix(n, unappetizingness, un, appetizingness).
negprefix(n, disobedience, dis, obedience).
negprefix(n, ungraciousness, un, graciousness).
negprefix(n, immortality, im, mortality).
negprefix(n, unequivocalness, un, equivocalness).
negprefix(n, atheism, a, theism).
negprefix(n, inactivity, in, activity).
negprefix(n, unobtrusiveness, un, obtrusiveness).
negprefix(n, illogicalness, il, logicalness).
negprefix(n, disesteem, dis, esteem).
negprefix(n, disfluency, dis, fluency).
negprefix(n, injudiciousness, in, judiciousness).
negprefix(n, invisibility, in, visibility).
negprefix(n, immotility, im, motility).
negprefix(n, discontinuance, dis, continuance).
negprefix(n, incaution, in, caution).
negprefix(n, inconstancy, in, constancy).
negprefix(n, irresponsibleness, ir, responsibleness).
negprefix(n, inhospitableness, in, hospitableness).
negprefix(n, unexchangeability, un, exchangeability).
negprefix(n, inactivation, in, activation).
negprefix(n, disservice, dis, service).
negprefix(n, immovableness, im, movableness).
negprefix(n, inequity, in, equity).
negprefix(n, unemployment, un, employment).
negprefix(n, insubordination, in, subordination).
negprefix(n, indecorum, in, decorum).
negprefix(n, unimportance, un, importance).
negprefix(n, nondrinker, non, drinker).
negprefix(n, undependability, un, dependability).
negprefix(n, unrespectability, un, respectability).
negprefix(n, nonabsorbency, non, absorbency).
negprefix(n, inconvertibility, in, convertibility).
negprefix(n, unconsciousness, un, consciousness).
negprefix(n, unemotional_person, un, emotional_person).
negprefix(n, unalterability, un, alterability).
negprefix(n, nonproliferation, non, proliferation).
negprefix(n, imbalance, im, balance).
negprefix(n, anisotropy, an, isotropy).
negprefix(n, disassembly, dis, assembly).
negprefix(n, achromatic_color, a, chromatic_color).
negprefix(n, disappearance, dis, appearance).
negprefix(n, unstableness, un, stableness).
negprefix(n, insensibility, in, sensibility).
negprefix(n, inopportuneness, in, opportuneness).
negprefix(n, infidelity, in, fidelity).
negprefix(n, illicitness, il, licitness).
negprefix(n, distributary, dis, tributary).
negprefix(n, inanimateness, in, animateness).
negprefix(n, inerrancy, in, errancy).
negprefix(n, unfitness, un, fitness).
negprefix(n, immutableness, im, mutableness).
negprefix(n, 'non-dedicated_file_server', 'non-', dedicated_file_server).
negprefix(n, inconvenience, in, convenience).
negprefix(n, indecision, in, decision).
negprefix(n, infelicity, in, felicity).
negprefix(n, insolvency, in, solvency).
negprefix(n, disorderliness, dis, orderliness).
negprefix(n, unrelatedness, un, relatedness).
negprefix(n, intractability, in, tractability).
negprefix(n, nonconformity, non, conformity).
negprefix(n, unproductiveness, un, productiveness).
negprefix(n, incongruity, in, congruity).
negprefix(n, incompetence, in, competence).
negprefix(n, unapproachability, un, approachability).
negprefix(n, noncompliance, non, compliance).
negprefix(n, unholiness, un, holiness).
negprefix(n, inconsequence, in, consequence).
negprefix(n, unseemliness, un, seemliness).
negprefix(n, disequilibrium, dis, equilibrium).
negprefix(n, unpalatability, un, palatability).
negprefix(n, unsuitability, un, suitability).
negprefix(n, ineligibility, in, eligibility).
negprefix(n, inaccessibility, in, accessibility).
negprefix(n, irregularity, ir, regularity).
negprefix(n, irrelevance, ir, relevance).
negprefix(n, unbelief, un, belief).
negprefix(n, inhumaneness, in, humaneness).
negprefix(n, disreputability, dis, reputability).
negprefix(n, impotency, im, potency).
negprefix(n, unloading, un, loading).
negprefix(n, disassortative_mating, dis, assortative_mating).
negprefix(n, nonalignment, non, alignment).
negprefix(n, unfamiliarity, un, familiarity).
negprefix(n, unenlightenment, un, enlightenment).
negprefix(n, unvariedness, un, variedness).
negprefix(n, disconnectedness, dis, connectedness).
negprefix(n, indirectness, in, directness).
negprefix(n, uncommonness, un, commonness).
negprefix(n, incapableness, in, capableness).
negprefix(n, disenfranchisement, dis, enfranchisement).
negprefix(n, indecorousness, in, decorousness).
negprefix(n, undesirability, un, desirability).
negprefix(n, inequality, in, equality).
negprefix(n, discontentment, dis, contentment).
negprefix(n, dissimilitude, dis, similitude).
negprefix(n, incongruousness, in, congruousness).
negprefix(n, disinflation, dis, inflation).
negprefix(n, unadaptability, un, adaptability).
negprefix(n, unsuitableness, un, suitableness).
negprefix(n, insensitivity, in, sensitivity).
negprefix(n, unpretentiousness, un, pretentiousness).
negprefix(n, unreliableness, un, reliableness).
negprefix(n, inelegance, in, elegance).
negprefix(n, infertility, in, fertility).
negprefix(n, unsolvability, un, solvability).
negprefix(n, infeasibility, in, feasibility).
negprefix(n, nonuniformity, non, uniformity).
negprefix(n, unreality, un, reality).
negprefix(n, unpersuasiveness, un, persuasiveness).
negprefix(n, intangibility, in, tangibility).
negprefix(n, inappositeness, in, appositeness).


