:- module(negsuffix, [negsuffix/4]).

negsuffix(a, godless, less, god).
negsuffix(a, toneless, less, tone).
negsuffix(a, weaponless, less, weapon).
negsuffix(a, riskless, less, risk).
negsuffix(a, shiftless, less, shift).
negsuffix(a, motionless, less, motion).
negsuffix(a, penniless, less, penni).
negsuffix(a, forceless, less, force).
negsuffix(a, raimentless, less, raiment).
negsuffix(a, pathless, less, path).
negsuffix(a, collarless, less, collar).
negsuffix(a, sunless, less, sun).
negsuffix(a, meatless, less, meat).
negsuffix(a, errorless, less, error).
negsuffix(a, comfortless, less, comfort).
negsuffix(a, heatless, less, heat).
negsuffix(a, earless, less, ear).
negsuffix(a, lordless, less, lord).
negsuffix(a, petalless, less, petal).
negsuffix(a, rootless, less, root).
negsuffix(a, nerveless, less, nerve).
negsuffix(a, listless, less, list).
negsuffix(a, selfless, less, self).
negsuffix(a, odorless, less, odor).
negsuffix(a, recoilless, less, recoil).
negsuffix(a, flawless, less, flaw).
negsuffix(a, masterless, less, master).
negsuffix(a, painless, less, pain).
negsuffix(a, eyeless, less, eye).
negsuffix(a, featherless, less, feather).
negsuffix(a, handleless, less, handle).
negsuffix(a, lifeless, less, life).
negsuffix(a, rustless, less, rust).
negsuffix(a, loveless, less, love).
negsuffix(a, colorless, less, color).
negsuffix(a, boundless, less, bound).
negsuffix(a, lusterless, less, luster).
negsuffix(a, gutless, less, gut).
negsuffix(a, savorless, less, savor).
negsuffix(a, bellyless, less, belly).
negsuffix(a, memberless, less, member).
negsuffix(a, grassless, less, grass).
negsuffix(a, tensionless, less, tension).
negsuffix(a, scentless, less, scent).
negsuffix(a, roadless, less, road).
negsuffix(a, glassless, less, glass).
negsuffix(a, ribless, less, rib).
negsuffix(a, lustreless, less, lustre).
negsuffix(a, hairless, less, hair).
negsuffix(a, witless, less, wit).
negsuffix(a, pointless, less, point).
negsuffix(a, spineless, less, spine).
negsuffix(a, ductless, less, duct).
negsuffix(a, dowerless, less, dower).
negsuffix(a, dateless, less, date).
negsuffix(a, profitless, less, profit).
negsuffix(a, costless, less, cost).
negsuffix(a, mirthless, less, mirth).
negsuffix(a, homeless, less, home).
negsuffix(a, planless, less, plan).
negsuffix(a, christless, less, christ).
negsuffix(a, lossless, less, loss).
negsuffix(a, defenceless, less, defence).
negsuffix(a, weightless, less, weight).
negsuffix(a, windless, less, wind).
negsuffix(a, scaleless, less, scale).
negsuffix(a, gloveless, less, glove).
negsuffix(a, hapless, less, hap).
negsuffix(a, mateless, less, mate).
negsuffix(a, beltless, less, belt).
negsuffix(a, meaningless, less, meaning).
negsuffix(a, defenseless, less, defense).
negsuffix(a, tuneless, less, tune).
negsuffix(a, friendless, less, friend).
negsuffix(a, handless, less, hand).
negsuffix(a, limitless, less, limit).
negsuffix(a, clothesless, less, clothes).
negsuffix(a, hueless, less, hue).
negsuffix(a, baseless, less, base).
negsuffix(a, remorseless, less, remorse).
negsuffix(a, classless, less, class).
negsuffix(a, worthless, less, worth).
negsuffix(a, flowerless, less, flower).
negsuffix(a, chinless, less, chin).
negsuffix(a, lawless, less, law).
negsuffix(a, beardless, less, beard).
negsuffix(a, breastless, less, breast).
negsuffix(a, spiritless, less, spirit).
negsuffix(a, wingless, less, wing).
negsuffix(a, spotless, less, spot).
negsuffix(a, guileless, less, guile).
negsuffix(a, soundless, less, sound).
negsuffix(a, ageless, less, age).
negsuffix(a, hatless, less, hat).
negsuffix(a, mouthless, less, mouth).
negsuffix(a, winless, less, win).
negsuffix(a, matchless, less, match).
negsuffix(a, needless, less, need).
negsuffix(a, milkless, less, milk).
negsuffix(a, branchless, less, branch).
negsuffix(a, rudderless, less, rudder).
negsuffix(a, loamless, less, loam).
negsuffix(a, cheerless, less, cheer).
negsuffix(a, faultless, less, fault).
negsuffix(a, parentless, less, parent).
negsuffix(a, tongueless, less, tongue).
negsuffix(a, briefless, less, brief).
negsuffix(a, cloudless, less, cloud).
negsuffix(a, toothless, less, tooth).
negsuffix(a, motorless, less, motor).
negsuffix(a, rainless, less, rain).
negsuffix(a, wakeless, less, wake).
negsuffix(a, purposeless, less, purpose).
negsuffix(a, bibless, less, bib).
negsuffix(a, smokeless, less, smoke).
negsuffix(a, emotionless, less, emotion).
negsuffix(a, styleless, less, style).
negsuffix(a, bootless, less, boot).
negsuffix(a, shitless, less, shit).
negsuffix(a, stoneless, less, stone).
negsuffix(a, curtainless, less, curtain).
negsuffix(a, propertyless, less, property).
negsuffix(a, lipless, less, lip).
negsuffix(a, reasonless, less, reason).
negsuffix(a, wrinkleless, less, wrinkle).
negsuffix(a, edgeless, less, edge).
negsuffix(a, brimless, less, brim).
negsuffix(a, bodyless, less, body).
negsuffix(a, directionless, less, direction).
negsuffix(a, faithless, less, faith).
negsuffix(a, colourless, less, colour).
negsuffix(a, skinless, less, skin).
negsuffix(a, deathless, less, death).
negsuffix(a, measureless, less, measure).
negsuffix(a, groundless, less, ground).
negsuffix(a, powerless, less, power).
negsuffix(a, juiceless, less, juice).
negsuffix(a, odourless, less, odour).
negsuffix(a, footless, less, foot).
negsuffix(a, tearless, less, tear).
negsuffix(a, lidless, less, lid).
negsuffix(a, thriftless, less, thrift).
negsuffix(a, endless, less, end).
negsuffix(a, toeless, less, toe).
negsuffix(a, luckless, less, luck).
negsuffix(a, airless, less, air).
negsuffix(a, tailless, less, tail).
negsuffix(a, priceless, less, price).
negsuffix(a, voteless, less, vote).
negsuffix(a, landless, less, land).
negsuffix(a, flightless, less, flight).
negsuffix(a, roofless, less, roof).
negsuffix(a, heedless, less, heed).
negsuffix(a, strapless, less, strap).
negsuffix(a, crownless, less, crown).
negsuffix(a, weedless, less, weed).
negsuffix(a, brainless, less, brain).
negsuffix(a, speechless, less, speech).
negsuffix(a, savourless, less, savour).
negsuffix(a, fatherless, less, father).
negsuffix(a, chartless, less, chart).
negsuffix(a, fingerless, less, finger).
negsuffix(a, motherless, less, mother).
negsuffix(a, sexless, less, sex).
negsuffix(a, noseless, less, nose).
negsuffix(a, jawless, less, jaw).
negsuffix(a, bowelless, less, bowel).
negsuffix(a, aimless, less, aim).
negsuffix(a, tactless, less, tact).
negsuffix(a, cordless, less, cord).
negsuffix(a, passionless, less, passion).
negsuffix(a, heartless, less, heart).
negsuffix(a, valueless, less, value).
negsuffix(a, foodless, less, food).
negsuffix(a, beakless, less, beak).
negsuffix(a, talentless, less, talent).
negsuffix(a, ruthless, less, ruth).
negsuffix(a, humourless, less, humour).
negsuffix(a, countless, less, count).
negsuffix(a, starless, less, star).
negsuffix(a, stingless, less, sting).
negsuffix(a, tireless, less, tire).
negsuffix(a, offenseless, less, offense).
negsuffix(a, rhymeless, less, rhyme).
negsuffix(a, conscienceless, less, conscience).
negsuffix(a, soulless, less, soul).
negsuffix(a, legless, less, leg).
negsuffix(a, guiltless, less, guilt).
negsuffix(a, mindless, less, mind).
negsuffix(a, sinless, less, sin).
negsuffix(a, trackless, less, track).
negsuffix(a, aweless, less, awe).
negsuffix(a, fruitless, less, fruit).
negsuffix(a, motiveless, less, motive).
negsuffix(a, indexless, less, index).
negsuffix(a, stemless, less, stem).
negsuffix(a, childless, less, child).
negsuffix(a, bloodless, less, blood).
negsuffix(a, stateless, less, state).
negsuffix(a, restless, less, rest).
negsuffix(a, moonless, less, moon).
negsuffix(a, casteless, less, caste).
negsuffix(a, tubeless, less, tube).
negsuffix(a, viewless, less, view).
negsuffix(a, garmentless, less, garment).
negsuffix(a, sleeveless, less, sleeve).
negsuffix(a, thoughtless, less, thought).
negsuffix(a, effortless, less, effort).
negsuffix(a, punctureless, less, puncture).
negsuffix(a, rimless, less, rim).
negsuffix(a, sightless, less, sight).
negsuffix(a, ambitionless, less, ambition).
negsuffix(a, fernless, less, fern).
negsuffix(a, characterless, less, character).
negsuffix(a, wigless, less, wig).
negsuffix(a, treeless, less, tree).
negsuffix(a, ownerless, less, owner).
negsuffix(a, joyless, less, joy).
negsuffix(a, thornless, less, thorn).
negsuffix(a, resourceless, less, resource).
negsuffix(a, wordless, less, word).
negsuffix(a, meritless, less, merit).
negsuffix(a, dreamless, less, dream).
negsuffix(a, breathless, less, breath).
negsuffix(a, jobless, less, job).
negsuffix(a, frictionless, less, friction).
negsuffix(a, numberless, less, number).
negsuffix(a, slaveless, less, slave).
negsuffix(a, rimeless, less, rime).
negsuffix(a, fatless, less, fat).
negsuffix(a, waterless, less, water).
negsuffix(a, clueless, less, clue).
negsuffix(a, lightless, less, light).
negsuffix(a, wheelless, less, wheel).
negsuffix(a, armless, less, arm).
negsuffix(a, blameless, less, blame).
negsuffix(a, stainless, less, stain).
negsuffix(a, soleless, less, sole).
negsuffix(a, topless, less, top).
negsuffix(a, hornless, less, horn).
negsuffix(a, creaseless, less, crease).
negsuffix(a, formless, less, form).
negsuffix(a, changeless, less, change).
negsuffix(a, nameless, less, name).
negsuffix(a, helpless, less, help).
negsuffix(a, sleepless, less, sleep).
negsuffix(a, patronless, less, patron).
negsuffix(a, pilotless, less, pilot).
negsuffix(a, symptomless, less, symptom).
negsuffix(a, limbless, less, limb).
negsuffix(a, leadless, less, lead).
negsuffix(a, offenceless, less, offence).
negsuffix(a, timeless, less, time).
negsuffix(a, echoless, less, echo).
negsuffix(a, flavourless, less, flavour).
negsuffix(a, backless, less, back).
negsuffix(a, noiseless, less, noise).
negsuffix(a, expressionless, less, expression).
negsuffix(a, wireless, less, wire).
negsuffix(a, harmless, less, harm).
negsuffix(a, seamless, less, seam).
negsuffix(a, rayless, less, ray).
negsuffix(a, burdenless, less, burden).
negsuffix(a, shoeless, less, shoe).
negsuffix(a, futureless, less, future).
negsuffix(a, senseless, less, sense).
negsuffix(a, graceless, less, grace).
negsuffix(a, leafless, less, leaf).
negsuffix(a, goalless, less, goal).
negsuffix(a, hipless, less, hip).
negsuffix(a, sapless, less, sap).
negsuffix(a, voiceless, less, voice).
negsuffix(a, boughless, less, bough).
negsuffix(a, featureless, less, feature).
negsuffix(a, fearless, less, fear).
negsuffix(a, keyless, less, key).
negsuffix(a, hopeless, less, hope).
negsuffix(a, faceless, less, face).
negsuffix(a, starchless, less, starch).
negsuffix(a, supperless, less, supper).
negsuffix(a, drugless, less, drug).
negsuffix(a, tasteless, less, taste).
negsuffix(a, awnless, less, awn).
negsuffix(a, neckless, less, neck).
negsuffix(a, flavorless, less, flavor).
negsuffix(a, sugarless, less, sugar).
negsuffix(a, scoreless, less, score).
negsuffix(a, artless, less, art).
negsuffix(a, stalkless, less, stalk).
negsuffix(a, humorless, less, humor).
negsuffix(a, bottomless, less, bottom).
negsuffix(a, dripless, less, drip).
negsuffix(a, splinterless, less, splinter).
negsuffix(a, bedless, less, bed).
negsuffix(a, causeless, less, cause).
negsuffix(a, speckless, less, speck).
negsuffix(a, headless, less, head).
negsuffix(a, boneless, less, bone).
negsuffix(a, careless, less, care).
negsuffix(a, regardless, less, regard).
negsuffix(a, hitless, less, hit).
negsuffix(a, pulseless, less, pulse).
negsuffix(a, newsless, less, news).
negsuffix(a, springless, less, spring).
negsuffix(a, useless, less, use).
negsuffix(a, seedless, less, seed).
negsuffix(a, shapeless, less, shape).
negsuffix(a, moneyless, less, money).
negsuffix(a, whiskerless, less, whisker).
negsuffix(a, braless, less, bra).
negsuffix(a, ceaseless, less, cease).
negsuffix(a, peerless, less, peer).
negsuffix(a, shameless, less, shame).

negsuffix(r, shapelessly, less, shape).
negsuffix(r, bloodlessly, less, blood).
negsuffix(r, needlessly, less, need).
negsuffix(r, humourlessly, less, humour).
negsuffix(r, helplessly, less, help).
negsuffix(r, harmlessly, less, harm).
negsuffix(r, flawlessly, less, flaw).
negsuffix(r, sleeplessly, less, sleep).
negsuffix(r, soundlessly, less, sound).
negsuffix(r, thriftlessly, less, thrift).
negsuffix(r, defencelessly, less, defence).
negsuffix(r, tirelessly, less, tire).
negsuffix(r, pointlessly, less, point).
negsuffix(r, wordlessly, less, word).
negsuffix(r, powerlessly, less, power).
negsuffix(r, tastelessly, less, taste).
negsuffix(r, joylessly, less, joy).
negsuffix(r, tonelessly, less, tone).
negsuffix(r, breathlessly, less, breath).
negsuffix(r, speechlessly, less, speech).
negsuffix(r, tactlessly, less, tact).
negsuffix(r, painlessly, less, pain).
negsuffix(r, effortlessly, less, effort).
negsuffix(r, purposelessly, less, purpose).
negsuffix(r, fearlessly, less, fear).
negsuffix(r, uselessly, less, use).
negsuffix(r, profitlessly, less, profit).
negsuffix(r, motionlessly, less, motion).
negsuffix(r, gracelessly, less, grace).
negsuffix(r, endlessly, less, end).
negsuffix(r, senselessly, less, sense).
negsuffix(r, selflessly, less, self).
negsuffix(r, formlessly, less, form).
negsuffix(r, ceaselessly, less, cease).
negsuffix(r, defenselessly, less, defense).
negsuffix(r, hopelessly, less, hope).
negsuffix(r, lawlessly, less, law).
negsuffix(r, gainlessly, less, gain).
negsuffix(r, shamelessly, less, shame).
negsuffix(r, doubtlessly, less, doubt).
negsuffix(r, fruitlessly, less, fruit).
negsuffix(r, cheerlessly, less, cheer).
negsuffix(r, listlessly, less, list).
negsuffix(r, noiselessly, less, noise).
negsuffix(r, ruthlessly, less, ruth).
negsuffix(r, aimlessly, less, aim).
negsuffix(r, heartlessly, less, heart).
negsuffix(r, thoughtlessly, less, thought).
negsuffix(r, restlessly, less, rest).
negsuffix(r, worthlessly, less, worth).
negsuffix(r, mindlessly, less, mind).
negsuffix(r, heedlessly, less, heed).
negsuffix(r, faithlessly, less, faith).
negsuffix(r, soullessly, less, soul).
negsuffix(r, spotlessly, less, spot).
negsuffix(r, blamelessly, less, blame).
negsuffix(r, remorselessly, less, remorse).
negsuffix(r, faultlessly, less, fault).
negsuffix(r, boundlessly, less, bound).
negsuffix(r, artlessly, less, art).
negsuffix(r, nervelessly, less, nerve).
negsuffix(r, tunelessly, less, tune).
negsuffix(r, humorlessly, less, humor).
negsuffix(r, lifelessly, less, life).
negsuffix(r, carelessly, less, care).

negsuffix(n, pricelessness, less, price).
negsuffix(n, ruthlessness, less, ruth).
negsuffix(n, defenselessness, less, defense).
negsuffix(n, groundlessness, less, ground).
negsuffix(n, endlessness, less, end).
negsuffix(n, spiritlessness, less, spirit).
negsuffix(n, lifelessness, less, life).
negsuffix(n, lightlessness, less, light).
negsuffix(n, flawlessness, less, flaw).
negsuffix(n, colourlessness, less, colour).
negsuffix(n, spotlessness, less, spot).
negsuffix(n, blamelessness, less, blame).
negsuffix(n, waterlessness, less, water).
negsuffix(n, homelessness, less, home).
negsuffix(n, flavourlessness, less, flavour).
negsuffix(n, faithlessness, less, faith).
negsuffix(n, effortlessness, less, effort).
negsuffix(n, defencelessness, less, defence).
negsuffix(n, lusterlessness, less, luster).
negsuffix(n, cloudlessness, less, cloud).
negsuffix(n, talentlessness, less, talent).
negsuffix(n, aimlessness, less, aim).
negsuffix(n, tirelessness, less, tire).
negsuffix(n, sinlessness, less, sin).
negsuffix(n, windlessness, less, wind).
negsuffix(n, countlessness, less, count).
negsuffix(n, thoughtlessness, less, thought).
negsuffix(n, motionlessness, less, motion).
negsuffix(n, guiltlessness, less, guilt).
negsuffix(n, worthlessness, less, worth).
negsuffix(n, agelessness, less, age).
negsuffix(n, sleeplessness, less, sleep).
negsuffix(n, thriftlessness, less, thrift).
negsuffix(n, spinelessness, less, spine).
negsuffix(n, childlessness, less, child).
negsuffix(n, voicelessness, less, voice).
negsuffix(n, flavorlessness, less, flavor).
negsuffix(n, shapelessness, less, shape).
negsuffix(n, sightlessness, less, sight).
negsuffix(n, sexlessness, less, sex).
negsuffix(n, lawlessness, less, law).
negsuffix(n, soundlessness, less, sound).
negsuffix(n, savorlessness, less, savor).
negsuffix(n, bottomlessness, less, bottom).
negsuffix(n, artlessness, less, art).
negsuffix(n, senselessness, less, sense).
negsuffix(n, gutlessness, less, gut).
negsuffix(n, emotionlessness, less, emotion).
negsuffix(n, speechlessness, less, speech).
negsuffix(n, heedlessness, less, heed).
negsuffix(n, breathlessness, less, breath).
negsuffix(n, fruitlessness, less, fruit).
negsuffix(n, faultlessness, less, fault).
negsuffix(n, gracelessness, less, grace).
negsuffix(n, uselessness, less, use).
negsuffix(n, savourlessness, less, savour).
negsuffix(n, nervelessness, less, nerve).
negsuffix(n, tastelessness, less, taste).
negsuffix(n, fearlessness, less, fear).
negsuffix(n, weightlessness, less, weight).
negsuffix(n, godlessness, less, god).
negsuffix(n, heartlessness, less, heart).
negsuffix(n, ceaselessness, less, cease).
negsuffix(n, hopelessness, less, hope).
negsuffix(n, mindlessness, less, mind).
negsuffix(n, namelessness, less, name).
negsuffix(n, meaninglessness, less, meaning).
negsuffix(n, listlessness, less, list).
negsuffix(n, helplessness, less, help).
negsuffix(n, noiselessness, less, noise).
negsuffix(n, cheerlessness, less, cheer).
negsuffix(n, purposelessness, less, purpose).
negsuffix(n, changelessness, less, change).
negsuffix(n, shamelessness, less, shame).
negsuffix(n, lustrelessness, less, lustre).
negsuffix(n, carelessness, less, care).
negsuffix(n, restlessness, less, rest).
negsuffix(n, hairlessness, less, hair).
negsuffix(n, shiftlessness, less, shift).
negsuffix(n, selflessness, less, self).
negsuffix(n, friendlessness, less, friend).
negsuffix(n, joylessness, less, joy).
negsuffix(n, limitlessness, less, limit).
negsuffix(n, eyelessness, less, eye).
negsuffix(n, boundlessness, less, bound).
negsuffix(n, colorlessness, less, color).
negsuffix(n, risklessness, less, risk).
negsuffix(n, pointlessness, less, point).
negsuffix(n, tactlessness, less, tact).
negsuffix(n, pennilessness, less, penni).
negsuffix(n, timelessness, less, time).
negsuffix(n, valuelessness, less, value).
negsuffix(n, powerlessness, less, power).

