% Built by Ulf Hermjakob, USC/ISI - June 2, 2015
:- module(verbalization,[verbalize/2,verbalize/3,verbalize/4,verbalize/6]).

verbalize('abusive','abuse-01').
verbalize('acceptable','accept-01').
verbalize('accumulative','accumulate-01').
verbalize('accumulatively','accumulate-01').
verbalize('administrative','administrate-01').
verbalize('advisory','advise-01').
verbalize('afraid','fear-01').
verbalize('alive','live-01').
verbalize('anti','oppose-01').
verbalize('anti','counter-01').
verbalize('anti','destroy-01').
verbalize('asleep','sleep-01').
verbalize('attractive','attract-01').
verbalize('aware','realize-01').
verbalize('beneficial','benefit-01').
verbalize('coercive','coerce-01').
verbalize('commendable','commend-01').
verbalize('comparative','compare-01').
verbalize('comparatively','compare-01').
verbalize('competitive','compete-01').
verbalize('compliant','comply-01').
verbalize('compulsory','compel-01').
verbalize('consequently','cause-01').
verbalize('continual','continue-01').
verbalize('continuous','continue-01').
verbalize('cooperative','cooperate-01').
verbalize('dead','die-01').
verbalize('dead','kill-01').
verbalize('deadly','kill-01').
verbalize('destructive','destroy-01').
verbalize('detestable','detest-01').
verbalize('different','differ-02').
verbalize('discriminatory','discriminate-02').
verbalize('disgraceful','disgrace-01').
verbalize('disputable','dispute-01').
verbalize('dominant','dominate-01').
verbalize('educational','educate-01').
verbalize('eligible','qualify-02').
verbalize('emphatically','emphasize-01').
verbalize('expectantly','expect-01').
verbalize('exploratory','explore-01').
verbalize('fearful','fear-01').
verbalize('forceful','force-01').
verbalize('foreseeable','foresee-01').
verbalize('hallucinatory','hallucinate-01').
verbalize('hungry','hunger-01').
verbalize('imaginable','imagine-01').
verbalize('impressive','impress-01').
verbalize('inducible','induce-01').
verbalize('inflammatory','inflame-01').
verbalize('innovative','innovate-01').
verbalize('intrigueing','intrigue-01').
verbalize('investigative','investigate-01').
verbalize('justifiable','justify-01').
verbalize('legislative','legislate-01').
verbalize('measurable','measure-01').
verbalize('meritorious','merit-01').
verbalize('migratory','migrate-01').
verbalize('observational','observe-01').
verbalize('operational','operate-01').
verbalize('painful','pain-01').
verbalize('painfully','pain-01').
verbalize('precursory','precede-01').
verbalize('preferential','prefer-01').
verbalize('preparatory','prepare-02').
verbalize('presumably','presume-02').
verbalize('prevalent','prevail-02').
verbalize('proud','pride-01').
verbalize('prosperous','prosper-01').
verbalize('protective','protect-01').
verbalize('punishable','punish-01').
verbalize('putative','think-01').
verbalize('rebellious','rebel-01').
verbalize('rebuttal','rebut-01').
verbalize('regulatory','regulate-01').
verbalize('repeatedly','repeat-01').
verbalize('repressive','repress-01').
verbalize('resentful','resent-01').
verbalize('respectful','respect-01').
verbalize('rusty','rust-01').
verbalize('seemingly','seem-01').
verbalize('similar','resemble-01').
verbalize('similarity','resemble-01').
verbalize('stagnant','stagnate-01').
verbalize('successful','succeed-01').
verbalize('sufficient','suffice-01').
verbalize('surprisingly','surprise-01').
verbalize('taxable','tax-01').
verbalize('thirsty','thirst-01').
verbalize('traceable','trace-02').
verbalize('transferrable','transfer-01').
verbalize('voluntary','volunteer-01').
verbalize('willing','will-02').
verbalize('wishful','wish-01').
verbalize('continually','continue-01').
verbalize('increasingly','increase-01').
verbalize('overwhelmingly','overwhelm-01').
verbalize('reportedly','report-01').
verbalize('abrogation','abrogate-01').
verbalize('absolution','absolve-01').
verbalize('abstentia','absent-01').
verbalize('acetylation','acetylate-01').
verbalize('ad','advertise-01').
verbalize('adherence','adhere-02').
verbalize('administration','administrate-01').
verbalize('amination','aminate-01').
verbalize('apparition','appear-01').
verbalize('approval','approve-01').
verbalize('acquittal','acquit-01').
verbalize('annoyance','annoy-01').
verbalize('aspiration','aspire-01').
verbalize('baptism','baptize-01').
verbalize('behavior','behave-01').
verbalize('betrayal','betray-01').
verbalize('blessing','bless-01').
verbalize('blockage','block-01').
verbalize('bombing','bomb-01').
verbalize('breakaway','break-14').
verbalize('breakdown','break-12').
verbalize('breakup','break-08').
verbalize('coexistence','coexist-01').
verbalize('competition','compete-01').
verbalize('construction','construct-01').
verbalize('conversion','convert-01').
verbalize('cooperation','cooperate-01').
verbalize('crackdown','crack-06').
verbalize('creation','create-01').
verbalize('deacetylation','deacetylate-01').
verbalize('deceit','deceive-01').
verbalize('decryption','decrypt-00').
verbalize('demethylation','demethylate-01').
verbalize('dependence','depend-01').
verbalize('dependency','depend-01').
verbalize('dephosphorylation','dephosphorylate-01').
verbalize('descent','descend-01').
verbalize('desperation','despair-01').
verbalize('destruction','destroy-01').
verbalize('detention','detain-01').
verbalize('devaluation','devalue-01').
verbalize('development','develop-01').
verbalize('development','develop-02').
verbalize('dimerization','dimerize-00').
verbalize('disarmament','disarm-01').
verbalize('dominance','dominate-01').
verbalize('downregulation','downregulate-01').
verbalize('dysregulation','dysregulate-01').
verbalize('dysregulation','regulate-01').
verbalize('exclamation','exclaim-01').
verbalize('election','elect-01').
verbalize('elimination','eliminate-01').
verbalize('encryption','encrypt-01').
verbalize('espionage','spy-01').
verbalize('expectation','expect-01').
verbalize('failure','fail-01').
verbalize('flight','fly-01').
verbalize('flight','flee-01').
verbalize('forgiveness','forgive-01').
verbalize('fraud','defraud-01').
verbalize('globalization','globalize-01').
verbalize('habitation','inhabit-01').
verbalize('hesitancy','hesitate-01').
verbalize('heterodimerization','heterodimerize-00').
verbalize('hijacking','hijack-01').
verbalize('homodimerization','homodimerize-00').
verbalize('hydrolysis','hydrolyze-01').
verbalize('hypomethylation','methylate-01').
verbalize('infection','infect-01').
verbalize('invitation','invite-01').
verbalize('isomerization','isomerize-01').
verbalize('launching','launch-01').
verbalize('layoff','lay-02').
verbalize('liberation','liberate-01').
verbalize('methylation','methylate-01').
verbalize('misunderstanding','misunderstand-01').
verbalize('negligence','neglect-01').
verbalize('opposition','oppose-01').
verbalize('ouster','oust-01').
verbalize('perseverance','persevere-01').
verbalize('phosphorylation','phosphorylate-01').
verbalize('pretense','pretend-01').
verbalize('prosecution','prosecute-01').
verbalize('prosperity','prosper-01').
verbalize('radiance','radiate-01').
verbalize('reactivation','reactivate-01').
verbalize('reconciliation','reconcile-01').
verbalize('reconstruction','reconstruct-01').
verbalize('reelection','reelect-01').
verbalize('regulation','regulate-01').
verbalize('reintegration','reintegrate-01').
verbalize('repression','repress-01').
verbalize('reunification','re-unify-01').
verbalize('reverence','revere-01').
verbalize('robbery','rob-01').
verbalize('starvation','starve-01').
verbalize('subjugation','subjugate-01').
verbalize('subversion','subvert-01').
verbalize('suppression','suppress-01').
verbalize('surveillance','surveil-01').
verbalize('takeover','take-12').
verbalize('theft','steal-01').
verbalize('transaction','transact-01').
verbalize('transcription','transcribe-01').
verbalize('transfection','transfect-00').
verbalize('translocation','translocate-00').
verbalize('ubiquitination','ubiquitinate-01').
verbalize('upregulation','upregulate-01').
verbalize('weaponization','weaponize-01').
verbalize('victory','win-01').
verbalize('vision','see-01').
verbalize('vision','envision-01').
verbalize('capability','capable-41').
verbalize('freedom','free-41').
verbalize('intention','intent-41').
verbalize('responsibility','responsible-41').
verbalize('safety','safe-41').
verbalize('shortage','short-41').
verbalize('understandable','understand-01').

% verbalize/3
verbalize('unbiased','bias-01','polarity-').
verbalize('unburdened','burden-01','polarity-').
verbalize('uncensored','censor-01','polarity-').
verbalize('undecided','decide-01','polarity-').
verbalize('unedited','edit-01','polarity-').
verbalize('unexplored','explore-01','polarity-').
verbalize('unforeseen','foresee-01','polarity-').
verbalize('unfulfilled','fulfill-01','polarity-').
verbalize('unhindered','hinder-01','polarity-').
verbalize('unimpeded','impede-01','polarity-').
verbalize('unmaintained','maintain-01','polarity-').
verbalize('unmodified','modify-01','polarity-').
verbalize('unnamed','name-01','polarity-').
verbalize('unrealized','realize-02','polarity-').
verbalize('unrelenting','relent-01','polarity-').
verbalize('unsolved','solve-01','polarity-').
verbalize('unspecified','specify-01','polarity-').
verbalize('unsurpassed','surpass-01','polarity-').
verbalize('unswayed','sway-02','polarity-').

% verbalize/4
verbalize('abuser','person','ARG0-of','abuse-01').
verbalize('peacekeeping','keep-01','ARG1','peace').
verbalize('governmental','government-organization','ARG0-of','govern-01').
verbalize('activator','thing','ARG0-of','activate-01').
verbalize('actor','person','ARG0-of','act-01').
verbalize('actress','person','ARG0-of','act-01').
verbalize('administration','government-organization','ARG0-of','administrate-01').
verbalize('administration','organization','ARG0-of','administrate-01').
verbalize('administrator','person','ARG0-of','administrate-01').
verbalize('admirer','person','ARG0-of','admire-01').
verbalize('advertiser','company','ARG0-of','advertise-01').
verbalize('advertiser','person','ARG0-of','advertise-01').
verbalize('advisor','person','ARG0-of','advise-01').
verbalize('analyst','person','ARG0-of','analyze-01').
verbalize('announcer','person','ARG0-of','announce-01').
verbalize('applicant','person','ARG0-of','apply-01').
verbalize('assailant','person','ARG0-of','assail-01').
verbalize('assassin','person','ARG0-of','assassinate-01').
verbalize('assistant','person','ARG0-of','assist-01').
verbalize('attacker','person','ARG0-of','attack-01').
verbalize('attendee','person','ARG0-of','attend-01').
verbalize('auditor','person','ARG0-of','audit-01').
verbalize('author','person','ARG0-of','author-01').
verbalize('baker','person','ARG0-of','bake-01').
verbalize('beggar','person','ARG0-of','beg-01').
verbalize('believer','person','ARG0-of','believe-01').
verbalize('bidder','person','ARG0-of','bid-01').
verbalize('bomber','aircraft','ARG0-of','bomb-01').
verbalize('booster','person','ARG0-of','boost-01').
verbalize('broadcaster','company','ARG0-of','broadcast-01').
verbalize('buyer','person','ARG0-of','buy-01').
verbalize('campaigner','person','ARG0-of','campaign-01').
verbalize('capitulator','person','ARG0-of','capitulate-01').
verbalize('coach','person','ARG0-of','coach-01').
verbalize('combatant','person','ARG0-of','combat-01').
verbalize('competitor','person','ARG0-of','compete-01').
verbalize('composer','person','ARG0-of','compose-02').
verbalize('commuter','person','ARG0-of','commute-01').
verbalize('consultant','person','ARG0-of','consult-01').
verbalize('consumer','person','ARG0-of','consume-01').
verbalize('contributor','person','ARG0-of','contribute-01').
verbalize('controller','person','ARG0-of','control-01').
verbalize('creator','person','ARG0-of','create-01').
verbalize('dealer','person','ARG0-of','deal-01').
verbalize('dealer','person','ARG0-of','deal-02').
verbalize('dancer','person','ARG0-of','dance-01').
verbalize('defender','person','ARG0-of','defend-01').
verbalize('demonstrator','person','ARG0-of','demonstrate-01').
verbalize('designer','person','ARG0-of','design-01').
verbalize('deterrent','thing','ARG0-of','deter-01').
verbalize('detector','product','ARG0-of','detect-01').
verbalize('developer','person','ARG0-of','develop-02').
verbalize('devotee','person','ARG0-of','devote-01').
verbalize('digger','person','ARG0-of','dig-01').
verbalize('distributor','person','ARG0-of','distribute-01').
verbalize('donor','person','ARG0-of','donate-01').
verbalize('drafter','person','ARG0-of','draft-01').
verbalize('drinker','person','ARG0-of','drink-01').
verbalize('driver','person','ARG0-of','drive-01').
verbalize('eater','person','ARG0-of','eat-01').
verbalize('employer','organization','ARG0-of','employ-01').
verbalize('employer','company','ARG0-of','employ-01').
verbalize('employer','person','ARG0-of','employ-01').
verbalize('entertainer','person','ARG0-of','entertain-01').
verbalize('evaluator','person','ARG0-of','evaluate-01').
verbalize('explorer','person','ARG0-of','explore-01').
verbalize('extortionist','person','ARG0-of','extort-01').
verbalize('farmer','person','ARG0-of','farm-01').
verbalize('fertilizer','thing','ARG0-of','fertilize-01').
verbalize('fighter','aircraft','ARG0-of','fight-01').
verbalize('fighter','person','ARG0-of','fight-01').
verbalize('filter','product','ARG0-of','filter-01').
verbalize('financer','person','ARG0-of','finance-01').
verbalize('financier','person','ARG0-of','finance-01').
verbalize('fisherman','person','ARG0-of','fish-01').
verbalize('follower','person','ARG0-of','follow-02').
verbalize('founder','person','ARG0-of','found-01').
verbalize('government','government-organization','ARG0-of','govern-01').
verbalize('hacker','person','ARG0-of','hack-04').
verbalize('hijacker','person','ARG0-of','hijack-01').
verbalize('hitter','person','ARG0-of','hit-01').
verbalize('holder','person','ARG0-of','hold-01').
verbalize('hugger','person','ARG0-of','hug-01').
verbalize('hunter','person','ARG0-of','hunt-01').
verbalize('immigrant','person','ARG0-of','immigrate-01').
verbalize('incentive','thing','ARG0-of','incentivize-01').
verbalize('incinerator','facility','ARG0-of','incinerate-01').
verbalize('indicator','thing','ARG0-of','indicate-01').
verbalize('infiltrator','person','ARG0-of','infiltrate-01').
verbalize('inhabitant','person','ARG0-of','inhabit-01').
verbalize('inhibitor','thing','ARG0-of','inhibit-01').
verbalize('inspector','person','ARG0-of','inspect-01').
verbalize('interpreter','person','ARG0-of','interpret-01').
verbalize('investigator','person','ARG0-of','investigate-01').
verbalize('investor','person','ARG0-of','invest-01').
verbalize('jogger','person','ARG0-of','jog-01').
verbalize('judge','person','ARG0-of','judge-01').
verbalize('kidnapper','person','ARG0-of','kidnap-01').
verbalize('killer','person','ARG0-of','kill-01').
verbalize('laborer','person','ARG0-of','labor-01').
verbalize('launcher','product','ARG0-of','launch-01').
verbalize('lawmaker','person','ARG0-of','legislate-01').
verbalize('leader','person','ARG0-of','lead-01').
verbalize('leader','person','ARG0-of','lead-02').
verbalize('legislator','person','ARG0-of','legislate-01').
verbalize('legislature','government-organization','ARG0-of','legislate-01').
verbalize('liar','person','ARG0-of','lie-02').
verbalize('lobbyist','person','ARG0-of','lobby-01').
verbalize('maker','company','ARG0-of','make-01').
verbalize('maker','person','ARG0-of','make-01').
verbalize('manager','person','ARG0-of','manage-01').
verbalize('manufacturer','company','ARG0-of','manufacture-01').
verbalize('mediator','person','ARG0-of','mediate-01').
verbalize('merchant','person','ARG0-of','merchandise-01').
verbalize('migrant','person','ARG0-of','migrate-01').
verbalize('murderer','person','ARG0-of','murder-01').
verbalize('observer','person','ARG0-of','observe-01').
verbalize('offender','person','ARG0-of','offend-01').
verbalize('operator','person','ARG0-of','operate-01').
verbalize('opponent','person','ARG0-of','oppose-01').
verbalize('organizer','person','ARG0-of','organize-01').
verbalize('owner','person','ARG0-of','own-01').
verbalize('painter','person','ARG0-of','paint-01').
verbalize('painter','person','ARG0-of','paint-02').
verbalize('participant','person','ARG0-of','participate-01').
verbalize('passerby','person','ARG0-of','pass-17').
verbalize('performer','person','ARG0-of','perform-01').
verbalize('perpetrator','person','ARG0-of','perpetrate-01').
verbalize('planner','person','ARG0-of','plan-01').
verbalize('player','person','ARG0-of','play-01').
verbalize('preacher','person','ARG0-of','preach-01').
verbalize('producer','person','ARG0-of','produce-01').
verbalize('prosecutor','person','ARG0-of','prosecute-01').
verbalize('protester','person','ARG0-of','protest-01').
verbalize('provider','company','ARG0-of','provide-01').
verbalize('refinery','facility','ARG0-of','refine-01').
verbalize('reformer','person','ARG0-of','reform-01').
verbalize('publisher','company','ARG0-of','publish-01').
verbalize('rapist','person','ARG0-of','rape-01').
verbalize('reader','person','ARG0-of','read-01').
verbalize('recipient','thing','ARG0-of','receive-01').
verbalize('regulator','organization','ARG0-of','regulate-01').
verbalize('regulator','person','ARG0-of','regulate-01').
verbalize('reporter','person','ARG0-of','report-01').
verbalize('representative','person','ARG0-of','represent-01').
verbalize('repressor','protein','ARG0-of','repress-01').
verbalize('researcher','person','ARG0-of','research-01').
verbalize('resident','person','ARG0-of','reside-01').
verbalize('robber','person','ARG0-of','rob-01').
verbalize('runner','person','ARG0-of','run-02').
verbalize('sailor','person','ARG0-of','sail-01').
verbalize('seeker','person','ARG0-of','seek-01').
verbalize('seller','person','ARG0-of','sell-01').
verbalize('servant','person','ARG0-of','serve-01').
verbalize('servant','person','ARG0-of','serve-02').
verbalize('signatory','country','ARG0-of','sign-02').
verbalize('singer','person','ARG0-of','sing-01').
verbalize('smoker','person','ARG0-of','smoke-02').
verbalize('smuggler','person','ARG0-of','smuggle-01').
verbalize('speaker','person','ARG0-of','speak-01').
verbalize('specialist','person','ARG0-of','specialize-01').
verbalize('speculator','person','ARG0-of','speculate-01').
verbalize('spy','person','ARG0-of','spy-01').
verbalize('squatter','person','ARG0-of','squat-02').
verbalize('strategist','person','ARG0-of','strategize-01').
verbalize('striker','person','ARG0-of','strike-01').
verbalize('striker','person','ARG0-of','strike-02').
verbalize('student','person','ARG0-of','study-01').
verbalize('subscriber','person','ARG0-of','subscribe-01').
verbalize('sufferer','person','ARG0-of','suffer-01').
verbalize('supervisor','person','ARG0-of','supervise-01').
verbalize('supplier','country','ARG0-of','supply-01').
verbalize('supplier','company','ARG0-of','supply-01').
verbalize('supporter','person','ARG0-of','support-01').
verbalize('survivor','person','ARG0-of','survive-01').
verbalize('teacher','person','ARG0-of','teach-01').
verbalize('thief','person','ARG0-of','steal-01').
verbalize('tippler','person','ARG0-of','tipple-01').
verbalize('thrower','person','ARG0-of','throw-01').
verbalize('tourist','person','ARG0-of','tour-01').
verbalize('traitor','person','ARG0-of','betray-01').
verbalize('trafficker','person','ARG0-of','traffic-01').
verbalize('transferor','person','ARG0-of','transfer-01').
verbalize('translator','person','ARG0-of','translate-01').
verbalize('traveler','person','ARG0-of','travel-01').
verbalize('user','person','ARG0-of','use-01').
verbalize('vendor','company','ARG0-of','vend-01').
verbalize('vendor','person','ARG0-of','vend-01').
verbalize('victor','person','ARG0-of','win-01').
verbalize('visitor','person','ARG0-of','visit-01').
verbalize('voter','person','ARG0-of','vote-01').
verbalize('waiver','thing','ARG0-of','waive-01').
verbalize('winner','person','ARG0-of','win-01').
verbalize('wiper','thing','ARG0-of','wipe-01').
verbalize('worker','person','ARG0-of','work-01').
verbalize('writer','person','ARG0-of','write-01').
verbalize('drawing','picture','ARG1-of','draw-01').
verbalize('employee','person','ARG1-of','employ-01').
verbalize('expenditure','thing','ARG1-of','expend-01').
verbalize('expense','thing','ARG1-of','expend-01').
verbalize('hypothesis','thing','ARG1-of','hypothesize-01').
verbalize('intent','thing','ARG1-of','intend-01').
verbalize('opinion','thing','ARG1-of','opine-01').
verbalize('painting','picture','ARG1-of','paint-02').
verbalize('prisoner','person','ARG1-of','imprison-01').
verbalize('suggestion','thing','ARG1-of','suggest-01').
verbalize('surrounding','location','ARG1-of','surround-01').
verbalize('symbol','thing','ARG1-of','symbolize-01').
verbalize('transferee','person','ARG1-of','transfer-01').
verbalize('yield','thing','ARG1-of','yield-03').
verbalize('blessing','thing','ARG2-of','bless-01').
verbalize('evacuee','person','ARG2-of','evacuate-01').
verbalize('justification','thing','ARG2-of','justify-01').
verbalize('summary','thing','ARG2-of','summarize-01').

% verbalize/6
verbalize('beekeeper','person','ARG0-of','keep-01','ARG1','bee').
verbalize('filmmaker','person','ARG0-of','make-01','ARG1','film').
verbalize('lamplighter','person','ARG0-of','light-01','ARG1','lamp').
verbalize('landowner','person','ARG0-of','own-01','ARG1','land').
verbalize('peacekeeper','person','ARG0-of','keep-01','ARG1','peace').
verbalize('playwright','person','ARG0-of','write-01','ARG1','play').
verbalize('taxpayer','person','ARG0-of','pay-01','ARG1','tax').
verbalize('watchmaker','person','ARG0-of','make-01','ARG1','watch').
verbalize('bassist','person','ARG0-of','play-01','ARG2','bass').
verbalize('bassoonist','person','ARG0-of','play-01','ARG2','bassoon').
verbalize('cellist','person','ARG0-of','play-01','ARG2','cello').
verbalize('clarinetist','person','ARG0-of','play-01','ARG2','clarinet').
verbalize('drummer','person','ARG0-of','play-01','ARG2','drum').
verbalize('flautist','person','ARG0-of','play-01','ARG2','flute').
verbalize('flutist','person','ARG0-of','play-01','ARG2','flute').
verbalize('hornist','person','ARG0-of','play-01','ARG2','horn').
verbalize('oboist','person','ARG0-of','play-01','ARG2','oboe').
verbalize('organist','person','ARG0-of','play-01','ARG2','organ').
verbalize('percussionist','person','ARG0-of','play-01','ARG2','percussion').
verbalize('pianist','person','ARG0-of','play-01','ARG2','piano').
verbalize('trombonist','person','ARG0-of','play-01','ARG2','trombone').
verbalize('trumpeter','person','ARG0-of','play-01','ARG2','trumpet').
verbalize('violinist','person','ARG0-of','play-01','ARG2','violin').
verbalize('violist','person','ARG0-of','play-01','ARG2','viola').


